#!/usr/bin/env python3
"""Generate ../tests.json for the quicksort benchmark.

The expected outputs come from Python's sorted(), an oracle independent of the
Rust reference in this directory (which is then checked against them by run.sh).
The random arrays use splitmix64 so they can be regenerated in any language.
Run from anywhere: python3 gen_tests.py > ../tests.json
"""
import json
import sys

MASK = (1 << 64) - 1


class SplitMix64:
    def __init__(self, seed):
        self.state = seed & MASK

    def next(self):
        self.state = (self.state + 0x9E3779B97F4A7C15) & MASK
        z = self.state
        z = ((z ^ (z >> 30)) * 0xBF58476D1CE4E5B9) & MASK
        z = ((z ^ (z >> 27)) * 0x94D049BB133111EB) & MASK
        return z ^ (z >> 31)

    def below(self, n):
        return self.next() % n


HAND = [
    ("empty", []),
    ("one", [42]),
    ("two-sorted", [1, 2]),
    ("two-reversed", [2, 1]),
    ("duplicates", [3, 1, 3, 2, 1, 3, 0, 2]),
    ("sorted", list(range(1, 17))),
    ("reverse-sorted", list(range(16, 0, -1))),
    ("all-equal", [7] * 12),
    ("mixed", [5, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5, 0, 99]),
]

SEED = 20260930
N_RANDOM = 20
MAX_LEN = 64


def main():
    rng = SplitMix64(SEED)
    cases = [(name, xs) for name, xs in HAND]
    for i in range(N_RANDOM):
        # Case 0 has the maximum length; every fourth case draws from 0..3 for duplicates.
        n = MAX_LEN if i == 0 else rng.below(MAX_LEN + 1)
        hi = 4 if i % 4 == 3 else 100
        cases.append((f"random-{i:02d}", [rng.below(hi) for _ in range(n)]))
    out = ['{\n  "about": ' + json.dumps(
        "Quicksort test vectors; see SPEC.md section 6. Generated by _reference/gen_tests.py "
        f"(splitmix64, seed {SEED}); expected outputs from Python's sorted().") + ',\n  "cases": [\n']
    out.append(",\n".join(
        "    " + json.dumps({"name": name, "input": xs, "expected": sorted(xs)}) for name, xs in cases))
    out.append("\n  ]\n}\n")
    sys.stdout.write("".join(out))


if __name__ == "__main__":
    main()
