import Dllbc.Syntax
import Dllbc.Value
import Dllbc.Pure
import Dllbc.Machine
import Dllbc.Boundary
import Dllbc.Macro
import Dllbc.Std
import Dllbc.PureMacro
import Dllbc.StdLemmas
import Dllbc.Tests.S2
import Dllbc.Tests.S3
import Dllbc.Tests.S3Sym
import Dllbc.Tests.S4Pure
import Dllbc.Tests.S5Bound
import Dllbc.Tests.S6Call
import Dllbc.Tests.S7Group
import Dllbc.Tests.S8Diff
import Dllbc.Tests.S9Diff
import Dllbc.Tests.S10Ford
import Dllbc.Tests.S11Lib
import Dllbc.Tests.S12Inst
import Dllbc.Tests.S14Bounds
import Dllbc.Tests.S15Elab
import Dllbc.Tests.S16Spec
import Dllbc.Tests.S17Spec
import Dllbc.Tests.S18Rewrite
import Dllbc.Tests.S19Partition
