import Pss.Syntax
import Pss.Star
import Pss.Reduction

/-!
# Plain parallel β-reduction and conversion for System λ⊲

§2 of `pss/docs/03-revised-proof.md`: the imported facts about **plain,
unconditional β** on this syntax — Church–Rosser (Lemma 2.1) via
Takahashi parallel reduction, the conversion relation `=β`
(`EqClosure Step`), its substitutivity and congruence kit, and the
constructor-stability of value reducts (feeding Corollary 2.3).

`Par` is `Pss.Confluence`'s guarded `Par` with **all guard machinery
deleted** (no context, no `≤*` premise, no SRE-TOPAPP — plain β is a
left-linear orthogonal system; doc §0/§2). That file is *not* imported;
the namespace `Pss.Semantic.Par` avoids any collision with `Pss.Par`.
-/

namespace Pss.Semantic

/-- Takahashi-style simultaneous (parallel) plain-β reduction (doc §2,
Lemma 2.1): simultaneously contract any set of non-overlapping β-redexes,
congruently in every position — bounds included ("the bound is just
another position"). -/
inductive Par : Term → Term → Prop where
  | var {x : Nat} : Par (.var x) (.var x)
  | top : Par .top .top
  | lam {a a' b b' : Term} :
      Par a a' → Par b b' → Par (.lam a b) (.lam a' b')
  | app {t t' u u' : Term} :
      Par t t' → Par u u' → Par (.app t u) (.app t' u')
  /-- Contract the head redex while reducing body and argument in
  parallel (the discarded bound `a` needs no premise). -/
  | beta {a b b' s s' : Term} :
      Par b b' → Par s s' → Par (.app (.lam a b) s) (b'.subst1 s')

/-- `t =β u` — β-conversion: the equivalence generated by `⟶` (doc §1). -/
abbrev Beta : Term → Term → Prop := EqClosure Step

/-! ## `⟶ ⊆ Par ⊆ ⟶*` and the `Steps` congruence kit -/

/-- Parallel reduction is reflexive (the empty redex set). -/
theorem Par.refl (t : Term) : Par t t := by
  sorry

/-- `⟶ ⊆ Par`: a single β-step is a parallel step. -/
theorem Par.of_step {t t' : Term} (h : Step t t') : Par t t' := by
  sorry

/-- `Par ⊆ ⟶*`: a parallel step sequentializes. -/
theorem Par.toSteps {t t' : Term} (h : Par t t') : Steps t t' := by
  sorry

/-- `⟶*` coincides with iterated parallel reduction. -/
theorem steps_iff_star_par {t u : Term} : Steps t u ↔ Star Par t u := by
  sorry

/-- `⟶*` congruence in function position. -/
theorem Steps.appL {t t' : Term} (u : Term) (h : Steps t t') :
    Steps (.app t u) (.app t' u) := by
  sorry

/-- `⟶*` congruence in argument position. -/
theorem Steps.appR (t : Term) {u u' : Term} (h : Steps u u') :
    Steps (.app t u) (.app t u') := by
  sorry

/-- `⟶*` congruence in bound position. -/
theorem Steps.lamBound {t t' : Term} (u : Term) (h : Steps t t') :
    Steps (.lam t u) (.lam t' u) := by
  sorry

/-- `⟶*` congruence in body position. -/
theorem Steps.lamBody (t : Term) {u u' : Term} (h : Steps u u') :
    Steps (.lam t u) (.lam t u') := by
  sorry

/-- `⟶*` congruence at an application, both positions. -/
theorem Steps.app {t t' u u' : Term} (ht : Steps t t') (hu : Steps u u') :
    Steps (.app t u) (.app t' u') := by
  sorry

/-- `⟶*` congruence at a λ, both positions. -/
theorem Steps.lam {a a' b b' : Term} (ha : Steps a a') (hb : Steps b b') :
    Steps (.lam a b) (.lam a' b') := by
  sorry

/-! ## Substitutivity (the Takahashi substitution lemma) -/

/-- A single β-step is stable under simultaneous substitution. -/
theorem Step.subst (σ : Nat → Term) {t t' : Term} (h : Step t t') :
    Step (t.subst σ) (t'.subst σ) := by
  sorry

/-- `⟶*` substitutivity in σ-calculus form: reduce the term and the
substitution simultaneously. -/
theorem Steps.subst {σ τ : Nat → Term} (hστ : ∀ x, Steps (σ x) (τ x))
    {t t' : Term} (h : Steps t t') : Steps (t.subst σ) (t'.subst τ) := by
  sorry

/-- **Parallel substitutivity** (Takahashi's substitution lemma, doc §2),
σ-calculus form: `Par` is closed under simultaneous substitution by
pointwise-`Par` substitutions. -/
theorem Par.subst {σ τ : Nat → Term} (hστ : ∀ x, Par (σ x) (τ x))
    {t t' : Term} (h : Par t t') : Par (t.subst σ) (t'.subst τ) := by
  sorry

/-- Parallel substitutivity, `subst1` form: the β-case combinator of the
diamond proof. -/
theorem Par.subst1 {b b' s s' : Term} (hb : Par b b') (hs : Par s s') :
    Par (b.subst1 s) (b'.subst1 s') := by
  sorry

/-! ## Diamond, confluence (Lemma 2.1), Church–Rosser -/

/-- The diamond property of parallel reduction (Takahashi; doc §2). -/
theorem Par.diamond {t t₁ t₂ : Term} (h₁ : Par t t₁) (h₂ : Par t t₂) :
    ∃ t₃, Par t₁ t₃ ∧ Par t₂ t₃ := by
  sorry

/-- Strip lemma: one parallel step against a `Par`-sequence. -/
theorem Par.strip {t t₁ t₂ : Term} (h₁ : Par t t₁) (h₂ : Star Par t t₂) :
    ∃ t₃, Star Par t₁ t₃ ∧ Par t₂ t₃ := by
  sorry

/-- **Lemma 2.1 (Church–Rosser), confluence half** (doc §2): `⟶` is
confluent. -/
theorem steps_confluent {t u₁ u₂ : Term}
    (h₁ : Steps t u₁) (h₂ : Steps t u₂) :
    ∃ d, Steps u₁ d ∧ Steps u₂ d := by
  sorry

/-- **Lemma 2.1, conversion half** (doc §2): `t =β u` iff `t, u` have a
common reduct. -/
theorem beta_iff_common_reduct {t u : Term} :
    Beta t u ↔ ∃ d, Steps t d ∧ Steps u d := by
  sorry

/-! ## The `=β` kit

`Beta` is `Star (Sym Step)`, so `Star.refl`/`Star.trans` apply directly;
the named helpers below are the doc-level equivalence/congruence API the
model files consume (doc Lemmas 4.4/4.5, FT cases DS-EQ/DS-FUN/DS-APP).
-/

/-- `=β` is reflexive. -/
theorem Beta.refl (t : Term) : Beta t t := by
  sorry

/-- `=β` is symmetric. -/
theorem Beta.symm {t u : Term} (h : Beta t u) : Beta u t := by
  sorry

/-- `=β` is transitive. -/
theorem Beta.trans {t u v : Term} (h₁ : Beta t u) (h₂ : Beta u v) :
    Beta t v := by
  sorry

/-- `⟶ ⊆ =β`. -/
theorem Beta.of_step {t u : Term} (h : Step t u) : Beta t u := by
  sorry

/-- `⟶* ⊆ =β`. -/
theorem Beta.of_steps {t u : Term} (h : Steps t u) : Beta t u := by
  sorry

/-- `=β` congruence in function position. -/
theorem Beta.appL {t t' : Term} (u : Term) (h : Beta t t') :
    Beta (.app t u) (.app t' u) := by
  sorry

/-- `=β` congruence in argument position. -/
theorem Beta.appR (t : Term) {u u' : Term} (h : Beta u u') :
    Beta (.app t u) (.app t u') := by
  sorry

/-- `=β` congruence at an application, both positions. -/
theorem Beta.app {t t' u u' : Term} (ht : Beta t t') (hu : Beta u u') :
    Beta (.app t u) (.app t' u') := by
  sorry

/-- `=β` congruence in bound position. -/
theorem Beta.lamBound {t t' : Term} (u : Term) (h : Beta t t') :
    Beta (.lam t u) (.lam t' u) := by
  sorry

/-- `=β` congruence in body position. -/
theorem Beta.lamBody (t : Term) {u u' : Term} (h : Beta u u') :
    Beta (.lam t u) (.lam t u') := by
  sorry

/-- `=β` congruence at a λ, both positions (the componentwise transport
of doc Lemma 4.4's MATCH case). -/
theorem Beta.lam {a a' b b' : Term} (ha : Beta a a') (hb : Beta b b') :
    Beta (.lam a b) (.lam a' b') := by
  sorry

/-- `=β` congruence under any simultaneous substitution. -/
theorem Beta.subst (σ : Nat → Term) {t t' : Term} (h : Beta t t') :
    Beta (t.subst σ) (t'.subst σ) := by
  sorry

/-- **`=β` substitutivity** (Lemma 2.1, doc §2):
`t =β t', s =β s' ⟹ [x↦s]t =β [x↦s']t'`. -/
theorem Beta.subst1 {t t' s s' : Term} (ht : Beta t t') (hs : Beta s s') :
    Beta (t.subst1 s) (t'.subst1 s') := by
  sorry

/-! ## Reducts of values keep their constructor (feeding Cor 2.3) -/

/-- A `⟶*`-reduct of a λ is a λ with componentwise-reduced bound and
body. -/
theorem steps_lam_inv {a b v : Term} (h : Steps (.lam a b) v) :
    ∃ a' b', v = .lam a' b' ∧ Steps a a' ∧ Steps b b' := by
  sorry

/-- `Top` only `⟶*`-reduces to itself. -/
theorem steps_top_inv {v : Term} (h : Steps .top v) : v = .top := by
  sorry

end Pss.Semantic
