-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [quicksort]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace quicksort

/-- [quicksort::partition]: loop body 0:
    Source: 'src/lib.rs', lines 27:4-32:5 -/
@[rust_loop_body]
def partition_loop.body
  (pivot : Std.U32) (iter : core.ops.range.Range Std.Usize) (s : Slice Std.U32)
  (i : Std.Usize) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × (Slice Std.U32) ×
    Std.Usize) ((Slice Std.U32) × Std.Usize))
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done (s, i))
  | some j =>
    let i1 ← Slice.index_usize s j
    if i1 <= pivot
    then
      let s1 ← core.slice.Slice.swap s i j
      let i2 ← i + 1#usize
      ok (cont (iter1, s1, i2))
    else ok (cont (iter1, s, i))

/-- [quicksort::partition]: loop 0:
    Source: 'src/lib.rs', lines 27:4-32:5 -/
@[rust_loop]
def partition_loop
  (iter : core.ops.range.Range Std.Usize) (s : Slice Std.U32) (pivot : Std.U32)
  (i : Std.Usize) :
  Result ((Slice Std.U32) × Std.Usize)
  := do
  loop
    (fun (iter1, s1, i1) => partition_loop.body pivot iter1 s1 i1)
    (iter, s, i)

/-- [quicksort::partition]:
    Source: 'src/lib.rs', lines 22:0-36:1 -/
def partition (s : Slice Std.U32) : Result (Std.Usize × (Slice Std.U32)) := do
  let len := Slice.len s
  let i ← len - 1#usize
  let pivot ← Slice.index_usize s i
  let (s1, i1) ←
    partition_loop { start := 0#usize, «end» := i } s pivot 0#usize
  let i2 ← len - 1#usize
  let s2 ← core.slice.Slice.swap s1 i1 i2
  ok (i1, s2)

/-- [quicksort::quicksort]:
    Source: 'src/lib.rs', lines 48:0-66:1
    Visibility: public -/
def quicksort (s : Slice Std.U32) : Result (Slice Std.U32) := do
  let len := Slice.len s
  if len <= 1#usize
  then ok s
  else
    let (p, s1) ← partition s
    let (p1, split_at_mut_back) ← core.slice.Slice.split_at_mut s1 p
    let (lo, hi) := p1
    let lo1 ← quicksort lo
    let (p2, split_at_mut_back1) ← core.slice.Slice.split_at_mut hi 1#usize
    let (_pivot, upper) := p2
    let upper1 ← quicksort upper
    let hi1 := split_at_mut_back1 (_pivot, upper1)
    ok (split_at_mut_back (lo1, hi1))
partial_fixpoint

end quicksort
