# D67 (reborrow-and-replace accepted): meta-order's 1e003f84, the only change to the proof since 89899dad.
# Apply to sections/tf.typ ONLY once D67 is in the checker on ochr-core (same gate as D65), and cite Trav
# only if it lands in the suite. Usage: python3 d67_tf.py <paper dir>
import sys
P = sys.argv[1]
f = P + 'sections/tf.typ'
s = open(f).read()
PAIRS = [("  - An assignment's new value can be ended by the assignment's own [Access] on the symbolic path only: `x := Pick(n, &*x, &b)` ends the new borrow symbolically, while at `n = 1` the ground one survives. This is harmless for the drop clause. While the new value is in flight, the only drop is of the assigned place's old content. That content is a borrow, since the place has borrow type, so the drop ends it and never fails. After the assignment the value is a binding.", "  - An assignment's new value can be ended by the assignment's own [Access] on the symbolic path only: its loan can sit inside a neutral that the [Access] ends, while on the ground it sits where the [Access] leaves it. This is harmless for the drop clause. While the new value is in flight, the only drop is of the assigned place's old content. That content is a borrow, since the place has borrow type, so the drop ends it and never fails. After the assignment the value is a binding."), ("A [Match]'s [Access] ends only loans on the path and loans inside a neutral at the head, not loans deeper in a value. That is why the argument goes through the fill staying stuck. A program that reborrows through `Pick`'s result and then assigns `x := &c` is rejected on the symbolic path for this reason.", "A [Match]'s [Access] ends only loans on the path and loans inside a neutral at the head, not loans deeper in a value. An assignment's [Access] ends the loans in the part of the place's content that the place owns, and loans inside neutrals. A loan behind a borrow the place holds is left alone on both paths, and the drop of that borrow carries it back to its owner. In each case, an early end that the [Access] makes is made inside a neutral, so the argument goes through the fill staying stuck. A program that reborrows through `Pick`'s result and then assigns `x := &c` is rejected on the symbolic path for this reason."), ("The theorem does not cover the reborrow-and-replace idiom `x := &(*x).1`, because the rules reject it: the assignment's [Access] on `x` ends the new borrow, whose loan sits inside `x`'s content.", "The reborrow-and-replace idiom is in F, and it is accepted. `Trav(x : &Nat) : Unit := match *x { Z => (), S p => (x := &p; *x := 0) }` satisfies F1–F6. The new borrow's loan sits behind the borrow that `x` held, which the assignment's [Access] leaves alone. The drop of the old borrow carries the loan back to its owner, where it stays live. So @tf-thm covers it.")]
for o, n in PAIRS:
    assert s.count(o) == 1, o[:80]
    s = s.replace(o, n)
open(f, 'w').write(s)
print('ok')
