#import "../style.typ": *

We implemented the calculus as an executable reference checker in Lean 4, about 3,300 lines with no dependencies, plus about 1,200 lines of examples and tests. Its purpose is not performance but fidelity: a hand derivation can be charitable where the rules are silent, and a program cannot. Every example in this paper is checked by it, written in a concrete syntax close to the one used here:

```lean
ochr E1 {
  def AddM (x : &Nat) (y : Nat) : Unit by x :=
    match *x { Z => *x := y | S p => AddM(&p, y) }

  def AddMZero (x : &Nat) : Id Unit (AddM(x, 0)) () by x :=
    match *x { Z => refl | S p => AddMZero(&p) }

  reject def WriteThenRefl (x : &Nat) : Id Nat (*x) 5 := *x := 5; refl
}
```

A `def` is expected to be accepted and a `reject def` to be rejected, and each verdict is an assertion checked during the build, so a build succeeds only if every verdict is as expected. Each test file also asserts how many verdicts it contains, which guards against a test file that silently checks nothing.

*Structure.* The machine, closing off, sealed-program normalisation, splitting, closing off stuck blocks, observation, `Id`, [Call-type], [Def] and [Rec] form one mutually recursive block of about a thousand lines. Terms use de Bruijn indices, and the variables introduced by [Close] have fixed names, so "same normal form" is structural equality. The implementation follows the rules closely enough that its trace of `AddMZero` reproduces the derivation of @sec-overview symbol for symbol, including the successor that the environment supplies to the induction hypothesis.

*Test suite.* The suite contains every example of this paper: `AddM`, `AddMZero`, `Add` and `AddZero`; the returned-borrow examples `TailM`, `AddM'` and `AddMEq`; branching with borrows whose origin depends on the branch; opaque function arguments; the programs of @sec-overview that pass a proof about the current, mutated state; and user-declared inductive types, among them in-place list append and its returned-borrow variant, and the binary-search-tree insertion of @sec-overview with its size theorem. It also contains every program that must be rejected, in particular every closed false proof, and every accepted program that went wrong, found while designing the calculus.
// TODO(v2.0, lead): mention the v2.0 tests (False/True/And as declarations, match h {}, subsingleton elimination, disjointness, SubM's match h {}); update the verdict count (247 at d7e0be31), the timing (11.6 ms measured by reviewer-3) and the ledger row count (33), and the 24/6/2/1 split below, once the v2.0 checker lands. Also confirm that note 7's Q is now rejected (D44 in the checker), update the line counts above (3,334 + 1,228 at d7e0be31), and drop items from the "no row" list below if the v2.0 checker adds switches for them (and add rows for subsingleton elimination / match-by-type if it does).
All 247 verdicts are as expected. The compiled checker decides the whole suite in about 12 ms, the heaviest declaration (the size theorem) in under a millisecond; a clean build takes under half a minute, most of it spent re-running the suite for each row of the counterfactual ledger.

*The counterfactual ledger.* Each rule that is not the evident typing of a form has a switch that turns it off, and the build asserts, for each switch, exactly which verdicts flip when it is off. Of the 33 rows, 24 are _soundness_ rows: with the rule off, the checker accepts a program the rules reject, a closed proof of `False` or a program that goes wrong when run. Without entry-value recursion, the non-terminating "proofs" of @sec-typing are accepted; without exclusive access, an accepted program writes through an ended borrow; without the rule that a recursive function occurs only as the head of a call, a function that passes itself to a helper proves `False`; and without owner sets (@sec-obs), a function that returns a borrow into one of two arguments yields a closed proof of `False`. Six are _completeness_ rows: with the rule off, the checker only rejects programs it should accept. They are the private copy for erased terms (confinement now plays its soundness role; with both off, false proofs are accepted), generalising a sealed program before splitting on it, keeping it generalised when it is derived again, binding proof parameters to `⋆`, classifying a sequence as a proof by its tail, and [Seal]'s head guard for neutral-headed calls. Two rows, on how a variable is classified as a proof, flip nothing, because confinement subsumes them; with confinement also off, each admits false proofs. The last row switches _on_ an extension, confining the bodies of functions that return proofs or types, to record its cost: eleven good programs are rejected. The ledger shows that each rule is needed for some verdict, not that the rules suffice, and some side conditions have no row: non-cumulative universes, the borrow parameter of a borrow-returning Π-type, and the restrictions on where `&` may occur.

*What running the rules found.* Writing the checker exposed gaps in earlier versions of the rules, each now fixed: the recursive-function-as-a-value loophole above; an argument evaluated earlier in the same call being invalidated by a later one (`f(&x, x)` ends the first borrow while reading the second argument); recursive calls inside nested closures, which must be checked against the entry values of the enclosing function; and, with trees, the need to apply a split on a sealed program to re-derivations of it as well. The counterexamples summarised in @fig-why, including several that an earlier version of the checker accepted, are regression tests, and each soundness row of the ledger flips at least one of them.
