#import "../style.typ": *

*Functional translation of borrows.* Aeneas @aeneas translates safe Rust into a pure functional program in Lean, F\* or Coq. Its symbolic semantics of the low-level borrow calculus is the direct ancestor of our machine: we take its values with loans and borrows, its lazy ending of borrows, and its insight that a mutable borrow parameter is a forward computation plus a backward function. Later work gives that symbolic semantics joins and loops and proves it sound as a borrow checker @aeneas-borrowck. The difference is where and when the translation happens. Aeneas translates eagerly, whole-program, once, and the user reasons about the translated artifact, where backward functions are named definitions. Ochr never produces a translated program. The same state-passing content appears lazily inside conversion, only as far as a particular equation needs, and only in source syntax, but per call rather than per region, and without loops or nested borrows (@sec-eval). Aeneas is modular in that it never unfolds a callee; Ochr must unfold, because unfolding is what definitional equality is, and closing off is what keeps the unfolding finite. Electrolysis @electrolysis translated safe Rust into Lean before Aeneas, by the same functional reading of mutation.

*Prophecies.* RustHorn @rusthorn, RustHornBelt @rusthornbelt and Creusot @creusot model a mutable borrow as its current value paired with a _prophecy_ `^x` of its final value. A prophecy is available before it is resolved and specifications may mention it, which makes those specifications modular and lets them cover borrows stored in data and loops. Ochr's hole resembles an unresolved prophecy only superficially: it is inert, specifications cannot name it, and it exists only for borrows returned by stuck calls. Borrow parameters are modelled as Aeneas does, by an owned place whose content the call's end returns, and unlike prophecy-based models this needs the backward functions of borrow-returning functions to be injective (@sec-meta-model).

*Foundations of Rust's borrows.* RustBelt @rustbelt proves Rust's type system sound in a semantic model built in Iris, together with several standard libraries implemented with unsafe code, and Stacked Borrows @stacked-borrows and Tree Borrows @tree-borrows are operational aliasing models that say which accesses invalidate which pointers when unsafe code is present. Ochr's [Access] is a much coarser operational rule for safe code only, under which using a place ends every borrow derived from it; we have not related it to either model.

*Specification-based verification of imperative code.* Verus @verus, Creusot, Prusti @prusti, Flux @flux and VeriFast @verifast verify imperative code against specifications written separately, in pre- and postconditions, refinement types or separation logic, and discharge the obligations with automated provers. RefinedRust @refinedrust and Gillian-Rust @gillian-rust extend such verification to unsafe code, RefinedRust with a foundational soundness proof, and SPARK @spark-pointers adds Rust-like ownership and borrowing to Ada so that its deductive verifier can reason about pointers. Low\* @lowstar and Cogent @cogent (@sec-intro-two) still keep the proof apart from the program: a Low\* proof uses a function's pre- and postconditions over a memory model, and a Cogent proof is about the functional semantics that the compiler generates in Isabelle/HOL, whereas Ochr's conversion unfolds the in-place code itself. Hoare type theory @htt and Ynot @ynot internalise the triples in a dependent type theory, as do F\*'s separation-logic DSLs Steel and Pulse @steel; F\*'s Dijkstra monads @fstar-dm4free internalise weakest preconditions, and `reify` turns a stateful computation into a state-passing function, so two programs can be compared through their reified pure functions. In Ochr the specification of an in-place function is another program, or a theorem about the function itself, equality of computations is a type, and it is decided on the effectful code by conversion where possible.

*Effects in dependent type theory.* The fire triangle @fire-triangle shows that substitution, dependent elimination and observable effects cannot coexist consistently, and ∂CBPV organises the possible compromises. Closed Ochr programs are not observably effectful in their sense (@sec-intro-why). For open terms Ochr takes the call-by-value way out, keeping dependent elimination and restricting substitution to values, which Pédrot and Tabareau illustrate with PML. Lepigre's PML @pml relaxes the syntactic value restriction to a semantic one: an argument need only be observationally equivalent to a value. Ochr's typing instead runs the argument and substitutes the value it computes. The call-by-value type theory that Pédrot and Tabareau obtain by translation into ∂CBPV has no dependent `let` and no large elimination, its types being syntactic values; Ochr computes its types by running the checked program, and has both. Zombie @zombie combines a logical fragment with a call-by-value programming fragment that allows general recursion: its types may mention arbitrary programs, an equation between programs is proved by evaluating both sides to a common term, and several of its typing rules apply only to values. Ochr shares the evaluation-based equality and the attention to values, for programs that are total but mutate their environment. Krishnaswami, Pradic and Benton @linear-dependent integrate linear and dependent types with linear state, but their types depend only on non-linear terms, so a type cannot mention the current contents of a linear resource, as Ochr's types do. Ahman's eMLTT @emltt equips computations with definitional equations from an algebraic theory of global state; Ochr's state is structured, local and borrow-shaped, and its equations come from running the program rather than from an axiomatised theory.

*Observational equality.* Observational type theory @ott @ott-now-for-good computes the equality type by the structure of the type: equality of pairs is a pair of equalities, equality of functions is pointwise. Ochr's `Eq` computes by the structure of constructor values (injectivity and disjointness), and `Id` applies the idea at the type of observations, which is why `Eq` stays primitive rather than an inductive family. Unlike OTT, Ochr compares functions by their generic observation rather than pointwise, and its cast `J` computes only on convertible endpoints. Pujet and Tabareau's impredicative OTT @ott-impredicative studies the same combination of an impredicative, definitionally proof-irrelevant `Prop` with a computing equality, and Gilbert et al. @sprop show why an eliminator of a definitionally irrelevant equality must not reduce on open terms, which is the reason for Ochr's rule for `J`.

*Inductive propositions.* Ochr's connectives are inductive declarations in `Prop`, as in Lean, Coq and Agda, rather than impredicative encodings such as `False := Π(P : Prop). P` from the calculus of constructions @coc, and matching on a proof follows Lean's subsingleton elimination @theory-of-lean.

*Pure languages with in-place updates.* Lean 4 performs destructive updates on values it can prove unshared at runtime @counting-beans, and Koka's fully in-place fragment @fp2 guarantees statically that a function allocates nothing. Programs in these languages are pure, so their proofs are ordinary, but the programmer writes functional code and cannot express a borrow that is returned to the caller. Mutable value semantics @mvs reads an `inout` parameter as a function returning its new value, the reading that Aeneas and Ochr's sealed programs share, but as a programming discipline rather than for verification. Linear and quantitative type theories @qtt and ATS @ats track resources in types; Ochr uses the same separation between runtime usage and erased type-level usage as quantitative type theory, where a variable used in a type is not consumed.

*Relational reasoning.* ReLoC @reloc and relational Hoare logics prove two programs equivalent inside a program logic. Ochr's `Id` is a relational statement about two computations, but it is decided, where possible, by conversion, and it lives in the same type theory as the programs.
