#import "../style.typ": *

*Functional translation of borrows.* Aeneas @aeneas translates safe Rust into a pure functional program in Lean, F\* or Coq. Its symbolic semantics of the low-level borrow calculus is the direct ancestor of our machine: we take its values with loans and borrows, its lazy ending of borrows, and its insight that a mutable borrow parameter is a forward computation plus a backward function. Later work gives that symbolic semantics joins and loops and proves it sound as a borrow checker @aeneas-borrowck. The difference is where and when the translation happens. Aeneas translates eagerly, whole-program, once, and the user reasons about the translated artifact, where backward functions are named definitions. Ochr never produces a translated program. The same state-passing content appears lazily inside conversion, only as far as a particular equation needs, and only in source syntax: a sealed program is what Aeneas would call an application of a backward function. Aeneas is modular in that it never unfolds a callee; Ochr must unfold, because unfolding is what definitional equality is, and closing off is what keeps the unfolding finite.

*Prophecies.* RustHorn @rusthorn, RustHornBelt @rusthornbelt and Creusot @creusot model a mutable borrow as its current value paired with a _prophecy_ `^x` of its final value, resolved when the borrow ends. A filled loan in Ochr is a prophecy that has been resolved by the machine, and the hole in a sealed program for a returned borrow is an unresolved one. Prophecies are logic variables introduced at borrow creation; Ochr introduces no variables at all outside binders, which is what keeps concrete evaluation free of symbols (§@sec-meta).

*Specification-based verification of imperative code.* Verus @verus, Creusot, Prusti @prusti, Flux @flux and VeriFast @verifast verify imperative code against specifications written separately, in pre- and postconditions, refinement types or separation logic, and discharge the obligations with automated provers. Hoare type theory @htt and Ynot @ynot internalise the triples in a dependent type theory, as do F\*'s separation-logic DSLs Steel and Pulse @steel; F\*'s Dijkstra monads @fstar-dm4free internalise weakest preconditions and let `reify` turn a stateful computation into a state-passing function. Relational reasoning about two effectful programs is possible in some of these, notably through F\*'s `reify`, which exposes a stateful computation as a state-passing function that can then be compared; the comparison is about the reified pure function. In Ochr the specification of an in-place function is another program, or a theorem about the function itself, equality of computations is a type, and it is decided on the effectful code by conversion where possible.

*Effects in dependent type theory.* The fire triangle @fire-triangle shows that substitution, dependent elimination and observable effects cannot coexist consistently, and ∂CBPV organises the possible compromises. Closed Ochr programs are not observably effectful in their sense (@sec-intro-why). For open terms Ochr takes the call-by-value way out, keeping dependent elimination and restricting substitution to values, which Pédrot and Tabareau illustrate with PML. Lepigre's PML @pml relaxes the syntactic value restriction to a semantic one: an argument need only be observationally equivalent to a value. Ochr's typing instead runs the argument and substitutes the value it computes. The call-by-value type theory that Pédrot and Tabareau obtain by translation into ∂CBPV has no dependent `let` and no large elimination, its types being syntactic values; Ochr computes its types by running the checked program, and has both. Zombie @zombie combines a logical fragment with a call-by-value programming fragment that allows general recursion: its types may mention arbitrary programs, an equation between programs is proved by evaluating both sides to a common term, and several of its typing rules apply only to values. Ochr shares the evaluation-based equality and the attention to values, for programs that are total but mutate their environment. Ahman's eMLTT @emltt equips computations with definitional equations from an algebraic theory of global state; Ochr's state is structured, local and borrow-shaped, and its equations come from running the program rather than from an axiomatised theory.

*Observational equality.* Observational type theory @ott @ott-now-for-good computes the equality type by the structure of the type: equality of pairs is a pair of equalities, equality of functions is pointwise. Ochr's `Id` between computations is an instance of this idea at the type of observations, and it is why `Eq` stays primitive rather than an inductive family. We adopt the rules for pairs, for reflexive equations and for distinct constructors, which is what lets `Id` compute to the one interesting equation, or to `False`; injectivity of constructors (`Eq Nat (S a) (S b) ≡ Eq Nat a b`) would be sound in the same model and would remove the remaining congruence steps from pure proofs, and we leave it out deliberately (@sec-obs).

*Inductive propositions.* Ochr's connectives are inductive declarations in `Prop`, as in Lean (`inductive False : Prop`), Coq (`Inductive False : Prop := .`) and Agda (`data ⊥ : Set where`), and matching on a proof follows Lean's subsingleton elimination @theory-of-lean. Encodings such as `False := Π(P : Prop). P` belong to calculi without inductive types, such as the pure calculus of constructions @coc. Indexed families, and with them equality as an inductive family, are future work.

*Pure languages with in-place updates.* Lean 4 performs destructive updates on values it can prove unshared at runtime @counting-beans, and Koka's fully in-place fragment @fp2 guarantees statically that a function allocates nothing. Programs in these languages are pure, so their proofs are ordinary, but the programmer writes functional code and cannot express a borrow that is returned to the caller. Linear and quantitative type theories @qtt and ATS @ats track resources in types; Ochr uses the same separation between runtime usage and erased type-level usage as quantitative type theory, where a variable used in a type is not consumed.

*Relational reasoning.* ReLoC @reloc and relational Hoare logics prove two programs equivalent inside a program logic. Ochr's `Id` is a relational statement about two computations, but it is decided, where possible, by conversion, and it lives in the same type theory as the programs.
