// FIXED-BEGIN tests
// Transcribed mechanically from the benchmark's test vectors (tests.json), with V := u64. Do not edit.
use hashmap::HashMap;

#[test]
fn scripted() {
    let mut m: HashMap<u64> = HashMap::new(4);
    assert_eq!(m.get(0), None, "scripted op 0: get(0)");
    assert_eq!(m.len(), 0, "scripted op 0: len");
    assert_eq!(m.remove(3), None, "scripted op 1: remove(3)");
    assert_eq!(m.len(), 0, "scripted op 1: len");
    assert_eq!(m.insert(1, 10), None, "scripted op 2: insert(1, 10)");
    assert_eq!(m.len(), 1, "scripted op 2: len");
    assert_eq!(m.insert(5, 50), None, "scripted op 3: insert(5, 50)");
    assert_eq!(m.len(), 2, "scripted op 3: len");
    assert_eq!(m.insert(9, 90), None, "scripted op 4: insert(9, 90)");
    assert_eq!(m.len(), 3, "scripted op 4: len");
    assert_eq!(m.get(1), Some(&10), "scripted op 5: get(1)");
    assert_eq!(m.len(), 3, "scripted op 5: len");
    assert_eq!(m.get(5), Some(&50), "scripted op 6: get(5)");
    assert_eq!(m.len(), 3, "scripted op 6: len");
    assert_eq!(m.get(9), Some(&90), "scripted op 7: get(9)");
    assert_eq!(m.len(), 3, "scripted op 7: len");
    assert_eq!(m.get(13), None, "scripted op 8: get(13)");
    assert_eq!(m.len(), 3, "scripted op 8: len");
    assert_eq!(m.get(2), None, "scripted op 9: get(2)");
    assert_eq!(m.len(), 3, "scripted op 9: len");
    assert_eq!(m.insert(5, 55), Some(50), "scripted op 10: insert(5, 55)");
    assert_eq!(m.len(), 3, "scripted op 10: len");
    assert_eq!(m.get(5), Some(&55), "scripted op 11: get(5)");
    assert_eq!(m.len(), 3, "scripted op 11: len");
    assert_eq!(m.get(1), Some(&10), "scripted op 12: get(1)");
    assert_eq!(m.len(), 3, "scripted op 12: len");
    assert_eq!(m.get(9), Some(&90), "scripted op 13: get(9)");
    assert_eq!(m.len(), 3, "scripted op 13: len");
    assert_eq!(m.insert(0, 0), None, "scripted op 14: insert(0, 0)");
    assert_eq!(m.len(), 4, "scripted op 14: len");
    assert_eq!(m.insert(4, 40), None, "scripted op 15: insert(4, 40)");
    assert_eq!(m.len(), 5, "scripted op 15: len");
    assert_eq!(m.get(0), Some(&0), "scripted op 16: get(0)");
    assert_eq!(m.len(), 5, "scripted op 16: len");
    assert_eq!(m.remove(5), Some(55), "scripted op 17: remove(5)");
    assert_eq!(m.len(), 4, "scripted op 17: len");
    assert_eq!(m.get(5), None, "scripted op 18: get(5)");
    assert_eq!(m.len(), 4, "scripted op 18: len");
    assert_eq!(m.get(1), Some(&10), "scripted op 19: get(1)");
    assert_eq!(m.len(), 4, "scripted op 19: len");
    assert_eq!(m.get(9), Some(&90), "scripted op 20: get(9)");
    assert_eq!(m.len(), 4, "scripted op 20: len");
    assert_eq!(m.remove(5), None, "scripted op 21: remove(5)");
    assert_eq!(m.len(), 4, "scripted op 21: len");
    assert_eq!(m.remove(13), None, "scripted op 22: remove(13)");
    assert_eq!(m.len(), 4, "scripted op 22: len");
    assert_eq!(m.remove(1), Some(10), "scripted op 23: remove(1)");
    assert_eq!(m.len(), 3, "scripted op 23: len");
    assert_eq!(m.remove(9), Some(90), "scripted op 24: remove(9)");
    assert_eq!(m.len(), 2, "scripted op 24: len");
    assert_eq!(m.get(9), None, "scripted op 25: get(9)");
    assert_eq!(m.len(), 2, "scripted op 25: len");
    *m.get_mut(4) = 44;
    assert_eq!(m.len(), 2, "scripted op 26: len");
    assert_eq!(m.get(4), Some(&44), "scripted op 27: get(4)");
    assert_eq!(m.len(), 2, "scripted op 27: len");
    assert_eq!(m.get(0), Some(&0), "scripted op 28: get(0)");
    assert_eq!(m.len(), 2, "scripted op 28: len");
    *m.get_mut(0) = 7;
    assert_eq!(m.len(), 2, "scripted op 29: len");
    assert_eq!(m.get(0), Some(&7), "scripted op 30: get(0)");
    assert_eq!(m.len(), 2, "scripted op 30: len");
    assert_eq!(m.get(4), Some(&44), "scripted op 31: get(4)");
    assert_eq!(m.len(), 2, "scripted op 31: len");
    assert_eq!(m.insert(4, 45), Some(44), "scripted op 32: insert(4, 45)");
    assert_eq!(m.len(), 2, "scripted op 32: len");
    assert_eq!(m.insert(1, 11), None, "scripted op 33: insert(1, 11)");
    assert_eq!(m.len(), 3, "scripted op 33: len");
    assert_eq!(m.get(1), Some(&11), "scripted op 34: get(1)");
    assert_eq!(m.len(), 3, "scripted op 34: len");
    assert_eq!(m.insert(7, 70), None, "scripted op 35: insert(7, 70)");
    assert_eq!(m.len(), 4, "scripted op 35: len");
    assert_eq!(m.insert(3, 30), None, "scripted op 36: insert(3, 30)");
    assert_eq!(m.len(), 5, "scripted op 36: len");
    assert_eq!(m.insert(11, 99), None, "scripted op 37: insert(11, 99)");
    assert_eq!(m.len(), 6, "scripted op 37: len");
    *m.get_mut(3) = 33;
    assert_eq!(m.len(), 6, "scripted op 38: len");
    assert_eq!(m.get(7), Some(&70), "scripted op 39: get(7)");
    assert_eq!(m.len(), 6, "scripted op 39: len");
    assert_eq!(m.get(3), Some(&33), "scripted op 40: get(3)");
    assert_eq!(m.len(), 6, "scripted op 40: len");
    assert_eq!(m.get(11), Some(&99), "scripted op 41: get(11)");
    assert_eq!(m.len(), 6, "scripted op 41: len");
    assert_eq!(m.remove(11), Some(99), "scripted op 42: remove(11)");
    assert_eq!(m.len(), 5, "scripted op 42: len");
    assert_eq!(m.get(3), Some(&33), "scripted op 43: get(3)");
    assert_eq!(m.len(), 5, "scripted op 43: len");
    assert_eq!(m.remove(0), Some(7), "scripted op 44: remove(0)");
    assert_eq!(m.len(), 4, "scripted op 44: len");
    assert_eq!(m.get(4), Some(&45), "scripted op 45: get(4)");
    assert_eq!(m.len(), 4, "scripted op 45: len");
    assert_eq!(m.remove(4), Some(45), "scripted op 46: remove(4)");
    assert_eq!(m.len(), 3, "scripted op 46: len");
    assert_eq!(m.get(0), None, "scripted op 47: get(0)");
    assert_eq!(m.len(), 3, "scripted op 47: len");
    assert_eq!(m.get(4), None, "scripted op 48: get(4)");
    assert_eq!(m.len(), 3, "scripted op 48: len");
    assert_eq!(m.insert(0, 1), None, "scripted op 49: insert(0, 1)");
    assert_eq!(m.len(), 4, "scripted op 49: len");
    assert_eq!(m.get(0), Some(&1), "scripted op 50: get(0)");
    assert_eq!(m.len(), 4, "scripted op 50: len");
}

#[test]
fn random_cap1() {
    let mut m: HashMap<u64> = HashMap::new(1);
    assert_eq!(m.remove(2), None, "random-cap1 op 0: remove(2)");
    assert_eq!(m.len(), 0, "random-cap1 op 0: len");
    assert_eq!(m.insert(2, 27), None, "random-cap1 op 1: insert(2, 27)");
    assert_eq!(m.len(), 1, "random-cap1 op 1: len");
    assert_eq!(m.remove(2), Some(27), "random-cap1 op 2: remove(2)");
    assert_eq!(m.len(), 0, "random-cap1 op 2: len");
    assert_eq!(m.get(1), None, "random-cap1 op 3: get(1)");
    assert_eq!(m.len(), 0, "random-cap1 op 3: len");
    assert_eq!(m.get(3), None, "random-cap1 op 4: get(3)");
    assert_eq!(m.len(), 0, "random-cap1 op 4: len");
    assert_eq!(m.insert(0, 38), None, "random-cap1 op 5: insert(0, 38)");
    assert_eq!(m.len(), 1, "random-cap1 op 5: len");
    assert_eq!(m.insert(7, 65), None, "random-cap1 op 6: insert(7, 65)");
    assert_eq!(m.len(), 2, "random-cap1 op 6: len");
    assert_eq!(m.insert(4, 20), None, "random-cap1 op 7: insert(4, 20)");
    assert_eq!(m.len(), 3, "random-cap1 op 7: len");
    assert_eq!(m.get(4), Some(&20), "random-cap1 op 8: get(4)");
    assert_eq!(m.len(), 3, "random-cap1 op 8: len");
    *m.get_mut(7) = 79;
    assert_eq!(m.len(), 3, "random-cap1 op 9: len");
    assert_eq!(m.remove(2), None, "random-cap1 op 10: remove(2)");
    assert_eq!(m.len(), 3, "random-cap1 op 10: len");
    assert_eq!(m.insert(7, 78), Some(79), "random-cap1 op 11: insert(7, 78)");
    assert_eq!(m.len(), 3, "random-cap1 op 11: len");
    assert_eq!(m.remove(1), None, "random-cap1 op 12: remove(1)");
    assert_eq!(m.len(), 3, "random-cap1 op 12: len");
    assert_eq!(m.get(7), Some(&78), "random-cap1 op 13: get(7)");
    assert_eq!(m.len(), 3, "random-cap1 op 13: len");
    assert_eq!(m.get(7), Some(&78), "random-cap1 op 14: get(7)");
    assert_eq!(m.len(), 3, "random-cap1 op 14: len");
    *m.get_mut(0) = 41;
    assert_eq!(m.len(), 3, "random-cap1 op 15: len");
    assert_eq!(m.get(5), None, "random-cap1 op 16: get(5)");
    assert_eq!(m.len(), 3, "random-cap1 op 16: len");
    assert_eq!(m.insert(0, 8), Some(41), "random-cap1 op 17: insert(0, 8)");
    assert_eq!(m.len(), 3, "random-cap1 op 17: len");
    assert_eq!(m.remove(6), None, "random-cap1 op 18: remove(6)");
    assert_eq!(m.len(), 3, "random-cap1 op 18: len");
    assert_eq!(m.insert(2, 8), None, "random-cap1 op 19: insert(2, 8)");
    assert_eq!(m.len(), 4, "random-cap1 op 19: len");
    assert_eq!(m.get(4), Some(&20), "random-cap1 op 20: get(4)");
    assert_eq!(m.len(), 4, "random-cap1 op 20: len");
    assert_eq!(m.get(7), Some(&78), "random-cap1 op 21: get(7)");
    assert_eq!(m.len(), 4, "random-cap1 op 21: len");
    assert_eq!(m.remove(6), None, "random-cap1 op 22: remove(6)");
    assert_eq!(m.len(), 4, "random-cap1 op 22: len");
    *m.get_mut(4) = 86;
    assert_eq!(m.len(), 4, "random-cap1 op 23: len");
    assert_eq!(m.get(5), None, "random-cap1 op 24: get(5)");
    assert_eq!(m.len(), 4, "random-cap1 op 24: len");
    assert_eq!(m.insert(1, 19), None, "random-cap1 op 25: insert(1, 19)");
    assert_eq!(m.len(), 5, "random-cap1 op 25: len");
    assert_eq!(m.insert(2, 12), Some(8), "random-cap1 op 26: insert(2, 12)");
    assert_eq!(m.len(), 5, "random-cap1 op 26: len");
    assert_eq!(m.insert(7, 81), Some(78), "random-cap1 op 27: insert(7, 81)");
    assert_eq!(m.len(), 5, "random-cap1 op 27: len");
    assert_eq!(m.get(5), None, "random-cap1 op 28: get(5)");
    assert_eq!(m.len(), 5, "random-cap1 op 28: len");
    assert_eq!(m.remove(6), None, "random-cap1 op 29: remove(6)");
    assert_eq!(m.len(), 5, "random-cap1 op 29: len");
    assert_eq!(m.get(2), Some(&12), "random-cap1 op 30: get(2)");
    assert_eq!(m.len(), 5, "random-cap1 op 30: len");
    assert_eq!(m.get(0), Some(&8), "random-cap1 op 31: get(0)");
    assert_eq!(m.len(), 5, "random-cap1 op 31: len");
    assert_eq!(m.insert(4, 0), Some(86), "random-cap1 op 32: insert(4, 0)");
    assert_eq!(m.len(), 5, "random-cap1 op 32: len");
    assert_eq!(m.insert(7, 77), Some(81), "random-cap1 op 33: insert(7, 77)");
    assert_eq!(m.len(), 5, "random-cap1 op 33: len");
    assert_eq!(m.insert(5, 85), None, "random-cap1 op 34: insert(5, 85)");
    assert_eq!(m.len(), 6, "random-cap1 op 34: len");
    assert_eq!(m.insert(0, 0), Some(8), "random-cap1 op 35: insert(0, 0)");
    assert_eq!(m.len(), 6, "random-cap1 op 35: len");
    assert_eq!(m.insert(3, 71), None, "random-cap1 op 36: insert(3, 71)");
    assert_eq!(m.len(), 7, "random-cap1 op 36: len");
    assert_eq!(m.insert(0, 37), Some(0), "random-cap1 op 37: insert(0, 37)");
    assert_eq!(m.len(), 7, "random-cap1 op 37: len");
    *m.get_mut(4) = 85;
    assert_eq!(m.len(), 7, "random-cap1 op 38: len");
    *m.get_mut(2) = 26;
    assert_eq!(m.len(), 7, "random-cap1 op 39: len");
    assert_eq!(m.insert(3, 5), Some(71), "random-cap1 op 40: insert(3, 5)");
    assert_eq!(m.len(), 7, "random-cap1 op 40: len");
    assert_eq!(m.insert(0, 37), Some(37), "random-cap1 op 41: insert(0, 37)");
    assert_eq!(m.len(), 7, "random-cap1 op 41: len");
    assert_eq!(m.remove(6), None, "random-cap1 op 42: remove(6)");
    assert_eq!(m.len(), 7, "random-cap1 op 42: len");
    assert_eq!(m.insert(0, 71), Some(37), "random-cap1 op 43: insert(0, 71)");
    assert_eq!(m.len(), 7, "random-cap1 op 43: len");
    assert_eq!(m.insert(5, 9), Some(85), "random-cap1 op 44: insert(5, 9)");
    assert_eq!(m.len(), 7, "random-cap1 op 44: len");
    assert_eq!(m.insert(2, 42), Some(26), "random-cap1 op 45: insert(2, 42)");
    assert_eq!(m.len(), 7, "random-cap1 op 45: len");
    assert_eq!(m.insert(0, 11), Some(71), "random-cap1 op 46: insert(0, 11)");
    assert_eq!(m.len(), 7, "random-cap1 op 46: len");
    assert_eq!(m.insert(1, 25), Some(19), "random-cap1 op 47: insert(1, 25)");
    assert_eq!(m.len(), 7, "random-cap1 op 47: len");
    assert_eq!(m.get(0), Some(&11), "random-cap1 op 48: get(0)");
    assert_eq!(m.len(), 7, "random-cap1 op 48: len");
    *m.get_mut(0) = 84;
    assert_eq!(m.len(), 7, "random-cap1 op 49: len");
}

#[test]
fn random_cap3() {
    let mut m: HashMap<u64> = HashMap::new(3);
    assert_eq!(m.insert(6, 48), None, "random-cap3 op 0: insert(6, 48)");
    assert_eq!(m.len(), 1, "random-cap3 op 0: len");
    assert_eq!(m.insert(2, 20), None, "random-cap3 op 1: insert(2, 20)");
    assert_eq!(m.len(), 2, "random-cap3 op 1: len");
    assert_eq!(m.insert(3, 70), None, "random-cap3 op 2: insert(3, 70)");
    assert_eq!(m.len(), 3, "random-cap3 op 2: len");
    assert_eq!(m.remove(11), None, "random-cap3 op 3: remove(11)");
    assert_eq!(m.len(), 3, "random-cap3 op 3: len");
    assert_eq!(m.insert(11, 55), None, "random-cap3 op 4: insert(11, 55)");
    assert_eq!(m.len(), 4, "random-cap3 op 4: len");
    assert_eq!(m.insert(5, 53), None, "random-cap3 op 5: insert(5, 53)");
    assert_eq!(m.len(), 5, "random-cap3 op 5: len");
    *m.get_mut(6) = 36;
    assert_eq!(m.len(), 5, "random-cap3 op 6: len");
    assert_eq!(m.insert(5, 2), Some(53), "random-cap3 op 7: insert(5, 2)");
    assert_eq!(m.len(), 5, "random-cap3 op 7: len");
    assert_eq!(m.get(10), None, "random-cap3 op 8: get(10)");
    assert_eq!(m.len(), 5, "random-cap3 op 8: len");
    assert_eq!(m.remove(5), Some(2), "random-cap3 op 9: remove(5)");
    assert_eq!(m.len(), 4, "random-cap3 op 9: len");
    assert_eq!(m.insert(1, 97), None, "random-cap3 op 10: insert(1, 97)");
    assert_eq!(m.len(), 5, "random-cap3 op 10: len");
    assert_eq!(m.insert(0, 57), None, "random-cap3 op 11: insert(0, 57)");
    assert_eq!(m.len(), 6, "random-cap3 op 11: len");
    assert_eq!(m.insert(6, 18), Some(36), "random-cap3 op 12: insert(6, 18)");
    assert_eq!(m.len(), 6, "random-cap3 op 12: len");
    assert_eq!(m.get(3), Some(&70), "random-cap3 op 13: get(3)");
    assert_eq!(m.len(), 6, "random-cap3 op 13: len");
    assert_eq!(m.insert(2, 42), Some(20), "random-cap3 op 14: insert(2, 42)");
    assert_eq!(m.len(), 6, "random-cap3 op 14: len");
    assert_eq!(m.remove(0), Some(57), "random-cap3 op 15: remove(0)");
    assert_eq!(m.len(), 5, "random-cap3 op 15: len");
    assert_eq!(m.remove(0), None, "random-cap3 op 16: remove(0)");
    assert_eq!(m.len(), 5, "random-cap3 op 16: len");
    assert_eq!(m.insert(3, 18), Some(70), "random-cap3 op 17: insert(3, 18)");
    assert_eq!(m.len(), 5, "random-cap3 op 17: len");
    assert_eq!(m.insert(7, 12), None, "random-cap3 op 18: insert(7, 12)");
    assert_eq!(m.len(), 6, "random-cap3 op 18: len");
    *m.get_mut(6) = 40;
    assert_eq!(m.len(), 6, "random-cap3 op 19: len");
    *m.get_mut(2) = 53;
    assert_eq!(m.len(), 6, "random-cap3 op 20: len");
    *m.get_mut(3) = 31;
    assert_eq!(m.len(), 6, "random-cap3 op 21: len");
    assert_eq!(m.get(7), Some(&12), "random-cap3 op 22: get(7)");
    assert_eq!(m.len(), 6, "random-cap3 op 22: len");
    assert_eq!(m.insert(9, 60), None, "random-cap3 op 23: insert(9, 60)");
    assert_eq!(m.len(), 7, "random-cap3 op 23: len");
    assert_eq!(m.insert(8, 83), None, "random-cap3 op 24: insert(8, 83)");
    assert_eq!(m.len(), 8, "random-cap3 op 24: len");
    assert_eq!(m.insert(7, 66), Some(12), "random-cap3 op 25: insert(7, 66)");
    assert_eq!(m.len(), 8, "random-cap3 op 25: len");
    assert_eq!(m.get(11), Some(&55), "random-cap3 op 26: get(11)");
    assert_eq!(m.len(), 8, "random-cap3 op 26: len");
    assert_eq!(m.remove(8), Some(83), "random-cap3 op 27: remove(8)");
    assert_eq!(m.len(), 7, "random-cap3 op 27: len");
    assert_eq!(m.insert(11, 32), Some(55), "random-cap3 op 28: insert(11, 32)");
    assert_eq!(m.len(), 7, "random-cap3 op 28: len");
    assert_eq!(m.insert(8, 77), None, "random-cap3 op 29: insert(8, 77)");
    assert_eq!(m.len(), 8, "random-cap3 op 29: len");
    assert_eq!(m.insert(10, 73), None, "random-cap3 op 30: insert(10, 73)");
    assert_eq!(m.len(), 9, "random-cap3 op 30: len");
    assert_eq!(m.remove(0), None, "random-cap3 op 31: remove(0)");
    assert_eq!(m.len(), 9, "random-cap3 op 31: len");
    assert_eq!(m.get(11), Some(&32), "random-cap3 op 32: get(11)");
    assert_eq!(m.len(), 9, "random-cap3 op 32: len");
    assert_eq!(m.get(7), Some(&66), "random-cap3 op 33: get(7)");
    assert_eq!(m.len(), 9, "random-cap3 op 33: len");
    assert_eq!(m.get(4), None, "random-cap3 op 34: get(4)");
    assert_eq!(m.len(), 9, "random-cap3 op 34: len");
    assert_eq!(m.get(2), Some(&53), "random-cap3 op 35: get(2)");
    assert_eq!(m.len(), 9, "random-cap3 op 35: len");
    assert_eq!(m.insert(2, 53), Some(53), "random-cap3 op 36: insert(2, 53)");
    assert_eq!(m.len(), 9, "random-cap3 op 36: len");
    assert_eq!(m.get(2), Some(&53), "random-cap3 op 37: get(2)");
    assert_eq!(m.len(), 9, "random-cap3 op 37: len");
    assert_eq!(m.insert(4, 30), None, "random-cap3 op 38: insert(4, 30)");
    assert_eq!(m.len(), 10, "random-cap3 op 38: len");
    assert_eq!(m.remove(11), Some(32), "random-cap3 op 39: remove(11)");
    assert_eq!(m.len(), 9, "random-cap3 op 39: len");
    assert_eq!(m.remove(0), None, "random-cap3 op 40: remove(0)");
    assert_eq!(m.len(), 9, "random-cap3 op 40: len");
    assert_eq!(m.insert(0, 15), None, "random-cap3 op 41: insert(0, 15)");
    assert_eq!(m.len(), 10, "random-cap3 op 41: len");
    assert_eq!(m.insert(1, 20), Some(97), "random-cap3 op 42: insert(1, 20)");
    assert_eq!(m.len(), 10, "random-cap3 op 42: len");
    assert_eq!(m.insert(10, 20), Some(73), "random-cap3 op 43: insert(10, 20)");
    assert_eq!(m.len(), 10, "random-cap3 op 43: len");
    assert_eq!(m.insert(5, 90), None, "random-cap3 op 44: insert(5, 90)");
    assert_eq!(m.len(), 11, "random-cap3 op 44: len");
    assert_eq!(m.remove(7), Some(66), "random-cap3 op 45: remove(7)");
    assert_eq!(m.len(), 10, "random-cap3 op 45: len");
    *m.get_mut(4) = 40;
    assert_eq!(m.len(), 10, "random-cap3 op 46: len");
    assert_eq!(m.get(11), None, "random-cap3 op 47: get(11)");
    assert_eq!(m.len(), 10, "random-cap3 op 47: len");
    assert_eq!(m.insert(3, 75), Some(31), "random-cap3 op 48: insert(3, 75)");
    assert_eq!(m.len(), 10, "random-cap3 op 48: len");
    assert_eq!(m.insert(0, 29), Some(15), "random-cap3 op 49: insert(0, 29)");
    assert_eq!(m.len(), 10, "random-cap3 op 49: len");
}

#[test]
fn random_cap4() {
    let mut m: HashMap<u64> = HashMap::new(4);
    assert_eq!(m.insert(3, 6), None, "random-cap4 op 0: insert(3, 6)");
    assert_eq!(m.len(), 1, "random-cap4 op 0: len");
    *m.get_mut(3) = 19;
    assert_eq!(m.len(), 1, "random-cap4 op 1: len");
    assert_eq!(m.insert(1, 39), None, "random-cap4 op 2: insert(1, 39)");
    assert_eq!(m.len(), 2, "random-cap4 op 2: len");
    *m.get_mut(1) = 3;
    assert_eq!(m.len(), 2, "random-cap4 op 3: len");
    *m.get_mut(3) = 73;
    assert_eq!(m.len(), 2, "random-cap4 op 4: len");
    assert_eq!(m.get(1), Some(&3), "random-cap4 op 5: get(1)");
    assert_eq!(m.len(), 2, "random-cap4 op 5: len");
    assert_eq!(m.insert(12, 39), None, "random-cap4 op 6: insert(12, 39)");
    assert_eq!(m.len(), 3, "random-cap4 op 6: len");
    assert_eq!(m.insert(3, 19), Some(73), "random-cap4 op 7: insert(3, 19)");
    assert_eq!(m.len(), 3, "random-cap4 op 7: len");
    assert_eq!(m.insert(7, 84), None, "random-cap4 op 8: insert(7, 84)");
    assert_eq!(m.len(), 4, "random-cap4 op 8: len");
    assert_eq!(m.get(12), Some(&39), "random-cap4 op 9: get(12)");
    assert_eq!(m.len(), 4, "random-cap4 op 9: len");
    assert_eq!(m.remove(2), None, "random-cap4 op 10: remove(2)");
    assert_eq!(m.len(), 4, "random-cap4 op 10: len");
    assert_eq!(m.insert(0, 26), None, "random-cap4 op 11: insert(0, 26)");
    assert_eq!(m.len(), 5, "random-cap4 op 11: len");
    assert_eq!(m.insert(2, 10), None, "random-cap4 op 12: insert(2, 10)");
    assert_eq!(m.len(), 6, "random-cap4 op 12: len");
    assert_eq!(m.insert(5, 40), None, "random-cap4 op 13: insert(5, 40)");
    assert_eq!(m.len(), 7, "random-cap4 op 13: len");
    *m.get_mut(5) = 86;
    assert_eq!(m.len(), 7, "random-cap4 op 14: len");
    assert_eq!(m.get(4), None, "random-cap4 op 15: get(4)");
    assert_eq!(m.len(), 7, "random-cap4 op 15: len");
    assert_eq!(m.get(12), Some(&39), "random-cap4 op 16: get(12)");
    assert_eq!(m.len(), 7, "random-cap4 op 16: len");
    assert_eq!(m.insert(1, 59), Some(3), "random-cap4 op 17: insert(1, 59)");
    assert_eq!(m.len(), 7, "random-cap4 op 17: len");
    assert_eq!(m.get(4), None, "random-cap4 op 18: get(4)");
    assert_eq!(m.len(), 7, "random-cap4 op 18: len");
    assert_eq!(m.get(8), None, "random-cap4 op 19: get(8)");
    assert_eq!(m.len(), 7, "random-cap4 op 19: len");
    assert_eq!(m.remove(15), None, "random-cap4 op 20: remove(15)");
    assert_eq!(m.len(), 7, "random-cap4 op 20: len");
    assert_eq!(m.insert(15, 68), None, "random-cap4 op 21: insert(15, 68)");
    assert_eq!(m.len(), 8, "random-cap4 op 21: len");
    assert_eq!(m.insert(11, 80), None, "random-cap4 op 22: insert(11, 80)");
    assert_eq!(m.len(), 9, "random-cap4 op 22: len");
    assert_eq!(m.get(10), None, "random-cap4 op 23: get(10)");
    assert_eq!(m.len(), 9, "random-cap4 op 23: len");
    assert_eq!(m.remove(4), None, "random-cap4 op 24: remove(4)");
    assert_eq!(m.len(), 9, "random-cap4 op 24: len");
    assert_eq!(m.insert(13, 20), None, "random-cap4 op 25: insert(13, 20)");
    assert_eq!(m.len(), 10, "random-cap4 op 25: len");
    assert_eq!(m.insert(9, 7), None, "random-cap4 op 26: insert(9, 7)");
    assert_eq!(m.len(), 11, "random-cap4 op 26: len");
    *m.get_mut(5) = 30;
    assert_eq!(m.len(), 11, "random-cap4 op 27: len");
    assert_eq!(m.get(1), Some(&59), "random-cap4 op 28: get(1)");
    assert_eq!(m.len(), 11, "random-cap4 op 28: len");
    assert_eq!(m.remove(4), None, "random-cap4 op 29: remove(4)");
    assert_eq!(m.len(), 11, "random-cap4 op 29: len");
    assert_eq!(m.remove(10), None, "random-cap4 op 30: remove(10)");
    assert_eq!(m.len(), 11, "random-cap4 op 30: len");
    assert_eq!(m.get(13), Some(&20), "random-cap4 op 31: get(13)");
    assert_eq!(m.len(), 11, "random-cap4 op 31: len");
    assert_eq!(m.remove(9), Some(7), "random-cap4 op 32: remove(9)");
    assert_eq!(m.len(), 10, "random-cap4 op 32: len");
    *m.get_mut(7) = 75;
    assert_eq!(m.len(), 10, "random-cap4 op 33: len");
    assert_eq!(m.get(8), None, "random-cap4 op 34: get(8)");
    assert_eq!(m.len(), 10, "random-cap4 op 34: len");
    assert_eq!(m.remove(11), Some(80), "random-cap4 op 35: remove(11)");
    assert_eq!(m.len(), 9, "random-cap4 op 35: len");
    *m.get_mut(1) = 32;
    assert_eq!(m.len(), 9, "random-cap4 op 36: len");
    assert_eq!(m.get(6), None, "random-cap4 op 37: get(6)");
    assert_eq!(m.len(), 9, "random-cap4 op 37: len");
    assert_eq!(m.get(11), None, "random-cap4 op 38: get(11)");
    assert_eq!(m.len(), 9, "random-cap4 op 38: len");
    assert_eq!(m.get(4), None, "random-cap4 op 39: get(4)");
    assert_eq!(m.len(), 9, "random-cap4 op 39: len");
    assert_eq!(m.remove(6), None, "random-cap4 op 40: remove(6)");
    assert_eq!(m.len(), 9, "random-cap4 op 40: len");
    assert_eq!(m.insert(8, 82), None, "random-cap4 op 41: insert(8, 82)");
    assert_eq!(m.len(), 10, "random-cap4 op 41: len");
    assert_eq!(m.insert(3, 86), Some(19), "random-cap4 op 42: insert(3, 86)");
    assert_eq!(m.len(), 10, "random-cap4 op 42: len");
    assert_eq!(m.get(12), Some(&39), "random-cap4 op 43: get(12)");
    assert_eq!(m.len(), 10, "random-cap4 op 43: len");
    *m.get_mut(7) = 17;
    assert_eq!(m.len(), 10, "random-cap4 op 44: len");
    assert_eq!(m.get(10), None, "random-cap4 op 45: get(10)");
    assert_eq!(m.len(), 10, "random-cap4 op 45: len");
    assert_eq!(m.get(12), Some(&39), "random-cap4 op 46: get(12)");
    assert_eq!(m.len(), 10, "random-cap4 op 46: len");
    assert_eq!(m.remove(4), None, "random-cap4 op 47: remove(4)");
    assert_eq!(m.len(), 10, "random-cap4 op 47: len");
    assert_eq!(m.insert(7, 79), Some(17), "random-cap4 op 48: insert(7, 79)");
    assert_eq!(m.len(), 10, "random-cap4 op 48: len");
    assert_eq!(m.remove(2), Some(10), "random-cap4 op 49: remove(2)");
    assert_eq!(m.len(), 9, "random-cap4 op 49: len");
}

#[test]
fn random_cap7() {
    let mut m: HashMap<u64> = HashMap::new(7);
    assert_eq!(m.insert(10, 82), None, "random-cap7 op 0: insert(10, 82)");
    assert_eq!(m.len(), 1, "random-cap7 op 0: len");
    assert_eq!(m.insert(15, 33), None, "random-cap7 op 1: insert(15, 33)");
    assert_eq!(m.len(), 2, "random-cap7 op 1: len");
    assert_eq!(m.insert(0, 14), None, "random-cap7 op 2: insert(0, 14)");
    assert_eq!(m.len(), 3, "random-cap7 op 2: len");
    assert_eq!(m.insert(8, 60), None, "random-cap7 op 3: insert(8, 60)");
    assert_eq!(m.len(), 4, "random-cap7 op 3: len");
    assert_eq!(m.get(4), None, "random-cap7 op 4: get(4)");
    assert_eq!(m.len(), 4, "random-cap7 op 4: len");
    *m.get_mut(0) = 39;
    assert_eq!(m.len(), 4, "random-cap7 op 5: len");
    assert_eq!(m.get(3), None, "random-cap7 op 6: get(3)");
    assert_eq!(m.len(), 4, "random-cap7 op 6: len");
    assert_eq!(m.insert(19, 57), None, "random-cap7 op 7: insert(19, 57)");
    assert_eq!(m.len(), 5, "random-cap7 op 7: len");
    assert_eq!(m.remove(15), Some(33), "random-cap7 op 8: remove(15)");
    assert_eq!(m.len(), 4, "random-cap7 op 8: len");
    assert_eq!(m.insert(13, 82), None, "random-cap7 op 9: insert(13, 82)");
    assert_eq!(m.len(), 5, "random-cap7 op 9: len");
    assert_eq!(m.remove(18), None, "random-cap7 op 10: remove(18)");
    assert_eq!(m.len(), 5, "random-cap7 op 10: len");
    assert_eq!(m.remove(0), Some(39), "random-cap7 op 11: remove(0)");
    assert_eq!(m.len(), 4, "random-cap7 op 11: len");
    assert_eq!(m.get(13), Some(&82), "random-cap7 op 12: get(13)");
    assert_eq!(m.len(), 4, "random-cap7 op 12: len");
    assert_eq!(m.insert(5, 37), None, "random-cap7 op 13: insert(5, 37)");
    assert_eq!(m.len(), 5, "random-cap7 op 13: len");
    assert_eq!(m.insert(7, 48), None, "random-cap7 op 14: insert(7, 48)");
    assert_eq!(m.len(), 6, "random-cap7 op 14: len");
    assert_eq!(m.remove(7), Some(48), "random-cap7 op 15: remove(7)");
    assert_eq!(m.len(), 5, "random-cap7 op 15: len");
    assert_eq!(m.insert(23, 31), None, "random-cap7 op 16: insert(23, 31)");
    assert_eq!(m.len(), 6, "random-cap7 op 16: len");
    *m.get_mut(19) = 27;
    assert_eq!(m.len(), 6, "random-cap7 op 17: len");
    assert_eq!(m.get(1), None, "random-cap7 op 18: get(1)");
    assert_eq!(m.len(), 6, "random-cap7 op 18: len");
    assert_eq!(m.remove(3), None, "random-cap7 op 19: remove(3)");
    assert_eq!(m.len(), 6, "random-cap7 op 19: len");
    assert_eq!(m.insert(11, 18), None, "random-cap7 op 20: insert(11, 18)");
    assert_eq!(m.len(), 7, "random-cap7 op 20: len");
    assert_eq!(m.insert(5, 67), Some(37), "random-cap7 op 21: insert(5, 67)");
    assert_eq!(m.len(), 7, "random-cap7 op 21: len");
    assert_eq!(m.insert(20, 96), None, "random-cap7 op 22: insert(20, 96)");
    assert_eq!(m.len(), 8, "random-cap7 op 22: len");
    assert_eq!(m.get(12), None, "random-cap7 op 23: get(12)");
    assert_eq!(m.len(), 8, "random-cap7 op 23: len");
    assert_eq!(m.get(15), None, "random-cap7 op 24: get(15)");
    assert_eq!(m.len(), 8, "random-cap7 op 24: len");
    assert_eq!(m.get(5), Some(&67), "random-cap7 op 25: get(5)");
    assert_eq!(m.len(), 8, "random-cap7 op 25: len");
    assert_eq!(m.remove(9), None, "random-cap7 op 26: remove(9)");
    assert_eq!(m.len(), 8, "random-cap7 op 26: len");
    assert_eq!(m.insert(13, 87), Some(82), "random-cap7 op 27: insert(13, 87)");
    assert_eq!(m.len(), 8, "random-cap7 op 27: len");
    assert_eq!(m.get(19), Some(&27), "random-cap7 op 28: get(19)");
    assert_eq!(m.len(), 8, "random-cap7 op 28: len");
    *m.get_mut(11) = 84;
    assert_eq!(m.len(), 8, "random-cap7 op 29: len");
    assert_eq!(m.get(16), None, "random-cap7 op 30: get(16)");
    assert_eq!(m.len(), 8, "random-cap7 op 30: len");
    assert_eq!(m.insert(3, 78), None, "random-cap7 op 31: insert(3, 78)");
    assert_eq!(m.len(), 9, "random-cap7 op 31: len");
    assert_eq!(m.remove(4), None, "random-cap7 op 32: remove(4)");
    assert_eq!(m.len(), 9, "random-cap7 op 32: len");
    *m.get_mut(20) = 89;
    assert_eq!(m.len(), 9, "random-cap7 op 33: len");
    assert_eq!(m.get(0), None, "random-cap7 op 34: get(0)");
    assert_eq!(m.len(), 9, "random-cap7 op 34: len");
    assert_eq!(m.insert(23, 28), Some(31), "random-cap7 op 35: insert(23, 28)");
    assert_eq!(m.len(), 9, "random-cap7 op 35: len");
    assert_eq!(m.insert(20, 74), Some(89), "random-cap7 op 36: insert(20, 74)");
    assert_eq!(m.len(), 9, "random-cap7 op 36: len");
    assert_eq!(m.remove(5), Some(67), "random-cap7 op 37: remove(5)");
    assert_eq!(m.len(), 8, "random-cap7 op 37: len");
    assert_eq!(m.insert(19, 32), Some(27), "random-cap7 op 38: insert(19, 32)");
    assert_eq!(m.len(), 8, "random-cap7 op 38: len");
    assert_eq!(m.remove(9), None, "random-cap7 op 39: remove(9)");
    assert_eq!(m.len(), 8, "random-cap7 op 39: len");
    assert_eq!(m.insert(11, 98), Some(84), "random-cap7 op 40: insert(11, 98)");
    assert_eq!(m.len(), 8, "random-cap7 op 40: len");
    assert_eq!(m.remove(13), Some(87), "random-cap7 op 41: remove(13)");
    assert_eq!(m.len(), 7, "random-cap7 op 41: len");
    assert_eq!(m.remove(11), Some(98), "random-cap7 op 42: remove(11)");
    assert_eq!(m.len(), 6, "random-cap7 op 42: len");
    assert_eq!(m.get(15), None, "random-cap7 op 43: get(15)");
    assert_eq!(m.len(), 6, "random-cap7 op 43: len");
    assert_eq!(m.get(11), None, "random-cap7 op 44: get(11)");
    assert_eq!(m.len(), 6, "random-cap7 op 44: len");
    *m.get_mut(3) = 16;
    assert_eq!(m.len(), 6, "random-cap7 op 45: len");
    assert_eq!(m.get(13), None, "random-cap7 op 46: get(13)");
    assert_eq!(m.len(), 6, "random-cap7 op 46: len");
    *m.get_mut(19) = 17;
    assert_eq!(m.len(), 6, "random-cap7 op 47: len");
    assert_eq!(m.get(5), None, "random-cap7 op 48: get(5)");
    assert_eq!(m.len(), 6, "random-cap7 op 48: len");
    assert_eq!(m.remove(14), None, "random-cap7 op 49: remove(14)");
    assert_eq!(m.len(), 6, "random-cap7 op 49: len");
}
// FIXED-END tests
