import PSS.Syntax
import PSS.Declarative

/-!
# Algorithmic Subtyping

Mechanisation of Figure 2 from the PSS paper: the algorithmic formulation
of subtyping for System λ_◁.

The algorithmic system reformulates subtyping as an abstract reduction system.
The key idea is that transitivity (DS-TRANS) is replaced by reduction rules,
so the algorithmic formulation is syntax-directed.

The judgments are mutually dependent and defined in a single `mutual` block:
- `Prevalid Γ` — context prevalidity (weaker than well-formedness)
- `AlgSub r Γ t u` — algorithmic `Γ ⊢_A t ◁ u`
- `TransSub Γ t u` — transitive subtyping `Γ ⊢_A t ≤* u`
- `SubRedStep Γ t t'` — subtype reduction `Γ ⊢_A t ≤→ t'`
- `EquivRedStep Γ t t'` — equivalence reduction `Γ ⊢_A t ≡→ t'`
-/

open Expr

/-!
## Evaluation contexts

The paper defines two families of evaluation context:

    E_≡ ::= [] | E_≡(t) | t(E_≡) | λx ≤ E_≡. t
    E_≤ ::= [] | E_≤(t)

`E_≡` allows reduction in all positions (function, argument, domain);
`E_≤` restricts to positive (covariant) positions only.

Rather than defining contexts as a separate datatype, we encode them as
congruence constructors on the reduction relations directly.
-/

mutual

/-- `Prevalid Γ` — context prevalidity (Figure 2, top-left).

    Weaker than well-formedness: only requires free variables of each
    binding to be in scope, not that the binding is well-formed. -/
inductive Prevalid : Ctx → Prop where
  /-- P-CTX1: `∅ prevalid` -/
  | nil : Prevalid []
  /-- P-CTX2: `Γ prevalid, fv(t) ⊆ dom(Γ) ⊢ (Γ, x ≤ t) prevalid` -/
  | cons {Γ : Ctx} {t : Expr} :
      Prevalid Γ → t.closedAt Γ.length = true →
      Prevalid (t :: Γ)

/-- `AlgSub r Γ t u` — algorithmic subtyping `Γ ⊢_A t ◁ u`.

    When `r = .sub`:  this is `Γ ⊢_A t ≤ u`.
    When `r = .equiv`: this is `Γ ⊢_A t ≡ u`. -/
inductive AlgSub : Rel → Ctx → Expr → Expr → Prop where
  /-- AS-REFL: `Γ prevalid ⊢ t ◁ t` -/
  | refl {r : Rel} {Γ : Ctx} {t : Expr} :
      Prevalid Γ → AlgSub r Γ t t
  /-- AS-LEFT: `t ◁→ t', t' ◁ u ⊢ t ◁ u`

      Reduce on the left (the subtype side). The ◁→ step is a subtype
      congruence step when r = .sub, or an equivalence congruence step
      when r = .equiv. -/
  | left_sub {Γ : Ctx} {t t' u : Expr} :
      SubRedStep Γ t t' → AlgSub .sub Γ t' u →
      AlgSub .sub Γ t u
  | left_equiv {Γ : Ctx} {t t' u : Expr} :
      EquivRedStep Γ t t' → AlgSub .equiv Γ t' u →
      AlgSub .equiv Γ t u
  /-- AS-RIGHT: `u ≡→ u', t ◁ u' ⊢ t ◁ u`

      Reduce on the right (the supertype side). Both modes use
      equivalence reduction on the right. -/
  | right {r : Rel} {Γ : Ctx} {t u u' : Expr} :
      EquivRedStep Γ u u' → AlgSub r Γ t u' →
      AlgSub r Γ t u

/-- `TransSub Γ t u` — transitive algorithmic subtyping `Γ ⊢_A t ≤* u`.

    The reflexive-transitive closure of algorithmic subtyping. Used as
    a premise in SRE-APP. -/
inductive TransSub : Ctx → Expr → Expr → Prop where
  /-- AST-SUB: `s ≤ u ⊢ s ≤* u` -/
  | base {Γ : Ctx} {s u : Expr} :
      AlgSub .sub Γ s u → TransSub Γ s u
  /-- AST-TRANS: `s ≤* t, t ≤* u ⊢ s ≤* u` -/
  | trans {Γ : Ctx} {s t u : Expr} :
      TransSub Γ s t → TransSub Γ t u → TransSub Γ s u

/-- `SubRedStep Γ t t'` — subtype reduction `Γ ⊢_A t ≤→ t'`.

    Generated by SRS-PROM, SRS-TOP, and the congruence/fun/eq closure rules
    restricted to positive (covariant) positions. -/
inductive SubRedStep : Ctx → Expr → Expr → Prop where
  /-- SRS-PROM: variable promotion. `x ≤ t ∈ Γ ⊢ x ≤→ t` -/
  | prom {Γ : Ctx} {k : Nat} {t : Expr} :
      Prevalid Γ → Γ.get? k = some t →
      SubRedStep Γ (.bvar k) (t.shift (k + 1) 0)
  /-- SRS-TOP: `t ≤→ Top` -/
  | top_ {Γ : Ctx} {t : Expr} :
      Prevalid Γ → SubRedStep Γ t .top
  /-- SR-CONG for E_≤: step in function position of application. -/
  | cong_app_fun {Γ : Ctx} {f f' a : Expr} :
      SubRedStep Γ f f' → SubRedStep Γ (.app f a) (.app f' a)
  /-- SR-FUN: step in body of lambda. -/
  | cong_fun_body {Γ : Ctx} {dom body body' : Expr} :
      SubRedStep (dom :: Γ) body body' →
      SubRedStep Γ (.lam dom body) (.lam dom body')
  /-- SR-EQ: equivalence reduction is a subtype reduction. -/
  | from_equiv {Γ : Ctx} {t t' : Expr} :
      EquivRedStep Γ t t' → SubRedStep Γ t t'

/-- `EquivRedStep Γ t t'` — equivalence reduction `Γ ⊢_A t ≡→ t'`.

    Generated by SRE-APP, SRE-TOPAPP, and the congruence/fun closure rules
    which allow reduction in all positions. -/
inductive EquivRedStep : Ctx → Expr → Expr → Prop where
  /-- SRE-APP: β-reduction (with subtype check on the argument).
      `s ≤* t ⊢ (λt.u)(s) ≡→ [x ↦ s]u` -/
  | app_beta {Γ : Ctx} {dom body arg : Expr} :
      TransSub Γ arg dom →
      EquivRedStep Γ (.app (.lam dom body) arg) (body.subst 0 arg)
  /-- SRE-TOPAPP: `Top(t) ≡→ Top` -/
  | top_app {Γ : Ctx} {t : Expr} :
      Prevalid Γ → EquivRedStep Γ (.app .top t) .top
  /-- SR-CONG for E_≡: step in function position of application. -/
  | cong_app_fun {Γ : Ctx} {f f' a : Expr} :
      EquivRedStep Γ f f' → EquivRedStep Γ (.app f a) (.app f' a)
  /-- SR-CONG for E_≡: step in argument position of application. -/
  | cong_app_arg {Γ : Ctx} {f a a' : Expr} :
      EquivRedStep Γ a a' → EquivRedStep Γ (.app f a) (.app f a')
  /-- SR-CONG for E_≡: step in domain of lambda. -/
  | cong_lam_dom {Γ : Ctx} {dom dom' body : Expr} :
      EquivRedStep Γ dom dom' →
      EquivRedStep Γ (.lam dom body) (.lam dom' body)
  /-- SR-FUN: step in body of lambda. -/
  | cong_lam_body {Γ : Ctx} {dom body body' : Expr} :
      EquivRedStep (dom :: Γ) body body' →
      EquivRedStep Γ (.lam dom body) (.lam dom body')

end

/-- Reflexive-transitive closure of equivalence reduction. -/
inductive EquivRedSteps : Ctx → Expr → Expr → Prop where
  | refl {Γ : Ctx} {t : Expr} : EquivRedSteps Γ t t
  | step {Γ : Ctx} {t t' u : Expr} :
      EquivRedStep Γ t t' → EquivRedSteps Γ t' u → EquivRedSteps Γ t u

/-- Algorithmic type equivalence (Section 6):
    `t ≡ u` iff `∃ s, t ≡→* s ∧ u ≡→* s` (common reduct). -/
def AlgEquiv (Γ : Ctx) (t u : Expr) : Prop :=
  ∃ s, EquivRedSteps Γ t s ∧ EquivRedSteps Γ u s

/-- Algorithmic subtyping (Section 6):
    `t ≤ u` iff `∃ s, t ≤→* s ∧ u ≡→* s` (the subtype reduces
    to something the supertype is equivalent to, up to ≤→ promotions). -/
def AlgSubtype (Γ : Ctx) (t u : Expr) : Prop :=
  ∃ s, TransSub Γ t s ∧ EquivRedSteps Γ u s
