import Pss.Mpss.DeBruijnTypeSafety

/-! # `Pss.DeBruijnSanity` — de Bruijn `#print axioms` audit

This audit module tracks the new de Bruijn endpoints separately from
`Pss.Sanity`, which still reports the locally-nameless headline closures until
the branch switches over atomically.
-/

namespace Pss
namespace DeBruijn

#print axioms Lemma_2_DeBruijn_DiamondMEqRedStar_of
#print axioms Lemma_2_DeBruijn_DiamondMEqRedChain_of
#print axioms Lemma_1_DeBruijn_StrongCommutativityStar_of
#print axioms Lemma_1_DeBruijn_StrongCommutativityChain_of
#print axioms EqDiamonds_proved
#print axioms Lemma_2_DeBruijn_DiamondMEqRedStar_proved
#print axioms Lemma_2_DeBruijn_DiamondMEqRedChain_proved
#print axioms Term.shift_scoped_inv
#print axioms Stack.Scoped.shift_inv
#print axioms Term.instantiate_succ_shift_zero
#print axioms Stack.instantiate_succ_shift_zero
#print axioms Stack.instantiate_one_shift_zero
#print axioms Stack.instantiate_two_shift_zero
#print axioms Stack.instantiate_three_shift_zero
#print axioms Stack.instantiate_four_shift_zero
#print axioms Stack.instantiate_five_shift_zero
#print axioms Stack.instantiate_six_shift_zero
#print axioms Stack.instantiate_seven_shift_zero
#print axioms Stack.instantiate_eight_shift_zero
#print axioms Term.instantiate_two_shift_zero
#print axioms Term.instantiate_three_shift_zero
#print axioms Term.instantiate_four_shift_zero
#print axioms Term.instantiate_five_shift_zero
#print axioms Term.instantiate_six_shift_zero
#print axioms Term.instantiate_seven_shift_zero
#print axioms Term.instantiate_eight_shift_zero
#print axioms Term.instantiate_nine_shift_zero
#print axioms Term.instantiate_two_shift_zero_tail
#print axioms Term.instantiate_three_shift_zero_tail
#print axioms Term.instantiate_four_shift_zero_tail
#print axioms Term.instantiate_five_shift_zero_tail
#print axioms Term.instantiate_six_shift_zero_tail
#print axioms Term.instantiate_seven_shift_zero_tail
#print axioms Term.instantiate_eight_shift_zero_tail
#print axioms Term.instantiate_nine_shift_zero_tail
#print axioms Term.instantiate_after_seven
#print axioms Term.instantiate_zero_after_seven
#print axioms Term.shiftBy_tail
#print axioms Term.shiftBy_zero_tail
#print axioms Term.instantiate_shiftBy_zero_tail
#print axioms Stack.shiftBy_tail
#print axioms Stack.shiftBy_zero_tail
#print axioms Stack.instantiate_shiftBy_zero_tail
#print axioms Term.instantiate_succ_after
#print axioms Term.instantiate_after_many
#print axioms Term.instantiate_after_two
#print axioms Term.instantiate_zero_after_two
#print axioms Term.instantiate_after_three
#print axioms Term.instantiate_zero_after_three
#print axioms Term.instantiate_after_four
#print axioms Term.instantiate_zero_after_four
#print axioms Term.instantiate_after_five
#print axioms Term.instantiate_zero_after_five
#print axioms Term.instantiate_after_six
#print axioms Term.instantiate_zero_after_six
#print axioms Ctx.length_instantiateBetaPrefix
#print axioms Prevalid.equ_under_two_heads_replace
#print axioms PrevalidExt.equ_under_two_heads_replace
#print axioms Ctx.subBinds_equ_under_two_heads_replace
#print axioms Prevalid.equ_under_three_heads_replace
#print axioms PrevalidExt.equ_under_three_heads_replace
#print axioms Ctx.subBinds_equ_under_three_heads_replace
#print axioms Ctx.subBinds_replaceAt_equ
#print axioms PrevalidExt.replaceAt_equ_same
#print axioms meqRed_equ_under_two_heads_replace_from_handlers
#print axioms msubRed_equ_under_two_heads_replace_from_handlers
#print axioms PrevalidExt.weaken_head_inv
#print axioms MEqRed.prevalidExt
#print axioms MSubRed.prevalidExt
#print axioms EqDiamonds.top
#print axioms EqDiamonds.bvar_any
#print axioms EqDiamonds.appTop_any
#print axioms EqDiamonds.appTop_any_from_left
#print axioms EqDiamonds.appTop_any_from_right
#print axioms diamond_appTop_eqStar_eqStar
#print axioms StrongCommutes.top
#print axioms StrongCommutes.bvar_any
#print axioms StrongCommutes.appTop_any
#print axioms StrongCommutes.appTop_any_from_left
#print axioms StrongCommutes.appTop_any_from_right
#print axioms commute_appTop_subStar_eqStar
#print axioms commute_appTop_subStep_eqStar_from_left
#print axioms commute_appTop_subStar_eqStep_from_right
#print axioms commute_appTop_subStep_eqStep_from_left
#print axioms commute_abs_subStep_eqStar_top_or_absAbs_from_left
#print axioms commute_abs_subStar_eqStep_top_or_absAbs_from_right
#print axioms commute_abs_subStep_eqStep_top_or_absAbs_from_left
#print axioms commute_abs_subStep_eqStep_top_or_absAbs_from_right
#print axioms commute_appAbs_subStep_topOrAppTop_eqStar_from_left
#print axioms commute_appAbs_subStep_topOrAppTop_eqStep_from_left
#print axioms commute_appAbs_subStep_beta_or_join_or_appAbs_from_left
#print axioms commute_appAbs_subStep_eqStar_beta_or_join_or_appAbs_from_left
#print axioms commute_appAbs_subStep_eqStep_beta_or_join_or_appAbs_from_left
#print axioms commute_appAbs_subStep_eqStar_of_branches_from_left
#print axioms commute_appAbs_subStep_eqStep_of_branches_from_left
#print axioms commute_appAbs_subStep_eqStar_of_diamond_or_structApp_from_left
#print axioms commute_appAbs_subStep_eqStar_of_diamond_or_appAbs_from_left
#print axioms commute_appAbs_subStep_eqStep_of_diamond_or_structApp_from_left
#print axioms commute_appAbs_subStep_eqStep_of_diamond_or_appAbs_from_left
#print axioms commute_appAbs_structApp_eqStep_sameArg_of_from_left
#print axioms commute_app_app_body_from_operator_join_of
#print axioms commute_abs_fun_fun_app_body_app_from_operator_join_of
#print axioms msub_abs_step_stackHead_transport_or_fOp_from_left
#print axioms commute_appAbs_structApp_eqStep_or_fOp_residual_from_left
#print axioms commute_appAbs_structApp_eqStep_of_fOp_handlers_from_left
#print axioms commute_appAbs_structApp_eqStep_of_body_fOp_replacements_from_left
#print axioms commute_appAbs_structApp_eqStep_of_body_fOp_star_replacements_from_left
#print axioms commute_appAbs_structApp_eqStep_of_body_fOp_msub_replacements_from_left
#print axioms commute_appAbs_structApp_eqStep_of_shifted_fOp_replacements_from_left
#print axioms commute_appAbs_structApp_eqStep_of_lifted_shifted_fOp_replacements_from_left
#print axioms commute_appAbs_structApp_eqStep_of_shifted_fOp_tail_lifts_from_left
#print axioms commute_appAbs_structApp_eqStep_of_argument_stack_lifted_fOp_tail_lifts_from_left
#print axioms commute_appAbs_structApp_eqStep_of_argument_replacement_fOp_tail_lifts_from_left
#print axioms diamond_abs_fOp_body_fixed_bound
#print axioms diamond_abs_fOp_body_fixed_bound_from_left
#print axioms diamond_abs_fOp_body_fixed_bound_star
#print axioms diamond_abs_fOp_bound_fixed_body
#print axioms diamond_abs_fOp_bound_fixed_body_from_left
#print axioms diamond_abs_fOp_targets_of_bound_body_joins_from_left
#print axioms diamond_abs_fOp_bound_fixed_body_star
#print axioms commute_abs_fOp_body_fixed_bound
#print axioms commute_abs_fOp_body_fixed_bound_from_left
#print axioms commute_abs_fOp_body_fixed_bound_star
#print axioms commute_abs_fOp_eq_bound_body_star
#print axioms commute_abs_fOp_bound_fixed_body
#print axioms commute_abs_fOp_bound_fixed_body_from_left
#print axioms commute_abs_fOp_targets_of_eq_bound_body_joins_from_left
#print axioms commute_abs_fOp_bound_fixed_body_star
#print axioms diamond_abs_fun_body_fixed_bound
#print axioms diamond_abs_fun_body_fixed_bound_from_left
#print axioms diamond_abs_fun_body_fixed_bound_star
#print axioms msubStar_abs_fun_body_equ_bound
#print axioms msubRedStar_abs_fun_body_equ_bound
#print axioms diamond_abs_fun_bound_fixed_body
#print axioms diamond_abs_fun_bound_fixed_body_from_left
#print axioms diamond_abs_fun_targets_of_bound_body_joins_from_left
#print axioms diamond_abs_fun_targets_of_bound_body_chains_from_left
#print axioms diamond_abs_fun_bound_body_chains_star
#print axioms commute_abs_fun_bound_body_equ_chains_star
#print axioms commute_abs_fun_bound_body_top_star
#print axioms diamond_abs_fun_bound_fixed_body_star
#print axioms commute_abs_fun_body_fixed_bound
#print axioms commute_abs_fun_body_fixed_bound_from_left
#print axioms commute_abs_fun_body_fixed_bound_star
#print axioms commute_abs_fun_bound_fixed_body
#print axioms commute_abs_fun_bound_fixed_body_from_left
#print axioms commute_abs_fun_targets_of_bound_body_joins_from_left
#print axioms MSub.weaken_head
#print axioms MSubStar.weaken_head
#print axioms commute_abs_fun_targets_of_bound_body_equ_chains_from_left
#print axioms commute_abs_fun_fun_equ_body_of
#print axioms commute_abs_fun_fun_top_body_of
#print axioms commute_abs_fun_fun_body_from_handlers_of
#print axioms commute_abs_fun_fun_pro_succ_body_of
#print axioms commute_abs_fun_fun_pro_head_body_of
#print axioms commute_abs_fun_fun_body_from_app_fun_handlers_of
#print axioms commute_abs_fun_fun_app_body_tAp_of
#print axioms commute_abs_fun_fun_body_from_app_cases_fun_handlers_of
#print axioms commute_abs_fun_fun_body_from_operator_join_app_cases_fun_handlers_of
#print axioms commute_abs_fun_fun_body_from_operator_join_app_cases_eq_replaced_of
#print axioms commute_abs_fun_fun_body_from_operator_join_app_cases_step_transport_of
#print axioms commute_abs_fun_fun_body_from_operator_join_app_cases_stack_handlers_of
#print axioms commute_abs_fun_fun_body_from_operator_join_app_cases_equ_stack_handlers_of
#print axioms commute_abs_fun_fun_body_from_operator_join_app_cases_recursive_stack_handlers_of
#print axioms commute_abs_fun_fun_body_from_operator_join_app_cases_residual_body_handlers_of
#print axioms commute_abs_fun_fun_body_from_operator_join_app_cases_residual_body_star_handlers_of
#print axioms commute_abs_fun_fun_body_from_operator_join_app_cases_bet_body_stack_handlers_of
#print axioms commute_abs_fun_fun_body_from_operator_join_app_cases_fop_body_equ_handlers_of
#print axioms commute_abs_fun_bound_fixed_body_star
#print axioms Theorem_3_DeBruijn_TransitivityIsAdmissible_of
#print axioms Theorem_3_DeBruijn_WSubMStar_toMSub_of
#print axioms Theorem_3_DeBruijn_WEquMStar_toMSub_of
#print axioms Theorem_3_DeBruijn_WSubMStar_toChainDiagram_of
#print axioms Theorem_3_DeBruijn_WEquMStar_toChainDiagram_of
#print axioms Theorem_3_DeBruijn_AbsFunctionBoundChainShapePayload_of
#print axioms AbsFunctionBoundChainDiagramPayload_of_wsubm
#print axioms WSubM.abs_abs_chain_diagram
#print axioms WSubM.abs_function_bound_chain_diagram
#print axioms WSubM.abs_function_bound_inversion
#print axioms MSubRed.abs_function_bound_inversion
#print axioms Theorem_4_DeBruijn_NoTopFunctionSupertypesAt_of
#print axioms Theorem_4_DeBruijn_NoTopAbstractionSupertypesAt_of
#print axioms Theorem_4_DeBruijn_NoTopFunctionSupertypes_of
#print axioms MEqRedAppFunctionSupertypePayload.not_of_no_top
#print axioms MEqRedStackPreservesWSubMStarLeft.not_of_no_top
#print axioms MEqRedFOpBodyPayload.not_of_no_top
#print axioms MEqRedPreservesWfMContextual.not_of_no_top
#print axioms WfMSubHeadToEquHeadPayload.not_of_no_top
#print axioms WfMHeadKindTransportPayload.not_of_no_top
#print axioms Theorem_4_DeBruijn_Progress_of_StrongCommutativity
#print axioms BetaInstantiationPreservesScoped
#print axioms BetaInstantiationPreservesPrevalidExtStack
#print axioms BetaInstantiationPreservesWSubMStar
#print axioms BetaInstantiationPreservesWSubM
#print axioms BetaInstantiationPreservesMEqRed
#print axioms BetaInstantiationPreservesMSubRed
#print axioms BetaInstantiationPreservesMEqRedStack
#print axioms BetaInstantiationPreservesMSubRedStack
#print axioms BetaInstantiationPreservesMSubRedMSubStar
#print axioms BetaInstantiationPreservesMSubRedStackMSubStar
#print axioms BetaInstantiationPreservesMSubRedProHeadPayload
#print axioms BetaInstantiationPreservesMSubRedProHeadMSubStarPayload
#print axioms BetaInstantiationPreservesMSubRedFunBodyMSubStarPayload
#print axioms BetaInstantiationPreservesMSubRedFOpBodyMSubStarPayload
#print axioms BetaInstantiationPreservesMSubRedUnderHeadMSubStarPayload
#print axioms BetaInstantiationPreservesPrevalidPrefix
#print axioms BetaInstantiationPreservesPrevalidExtUnderHeads
#print axioms BetaInstantiationPreservesMEqRedUnderHeadsStack.pro
#print axioms BetaInstantiationPreservesMEqRedUnderHeadStack
#print axioms BetaInstantiationPreservesMEqRedUnderHeadFunStackPayload
#print axioms BetaInstantiationPreservesMEqRedUnderHeadBetStackPayload
#print axioms BetaInstantiationPreservesMEqRedUnderHeadFOpStackPayload
#print axioms BetaInstantiationPreservesMSubRedUnderHeadProMSubStarPayload
#print axioms BetaInstantiationPreservesMSubRedUnderHeadFunMSubStarPayload
#print axioms BetaInstantiationPreservesMSubRedUnderHeadFOpMSubStarPayload
#print axioms BetaInstantiationPreservesMSubRedFunBodyHeadChangeMSubStarPayload
#print axioms BetaInstantiationPreservesMEqRed.of_stack
#print axioms BetaInstantiationPreservesMSubRed.of_stack
#print axioms BetaInstantiationPreservesMSubRedStackMSubStar.of_raw
#print axioms BetaInstantiationPreservesMSubRedMSubStar.of_stack
#print axioms BetaInstantiationPreservesMSubRedMSubStar.of_raw
#print axioms BetaInstantiationPreservesMEqRedStack.refl
#print axioms BetaInstantiationPreservesMEqRedUnderHeadStack.refl
#print axioms BetaInstantiationPreservesMSubRedStack.refl
#print axioms BetaInstantiationPreservesMEqRed.refl
#print axioms BetaInstantiationPreservesMSubRed.refl
#print axioms BetaInstantiationPreservesWfM.top
#print axioms BetaInstantiationPreservesWfM.var_zero
#print axioms BetaInstantiationPreservesWfM.var_succ_sub
#print axioms BetaInstantiationPreservesWfM.var_succ_equ
#print axioms BetaInstantiationPreservesWfM.var
#print axioms BetaInstantiationPreservesWfM.abs
#print axioms BetaInstantiationPreservesWfM.app
#print axioms BetaInstantiationPreservesWfM.app_of_wsubmstar
#print axioms BetaInstantiationPreservesWfM.top_cell
#print axioms BetaInstantiationPreservesWfM.var_cell
#print axioms BetaInstantiationPreservesWfM.dispatch
#print axioms BetaInstantiationPreservesWfM_partial_proved
#print axioms BetaInstantiationPreservesWSubMStar.sub
#print axioms BetaInstantiationPreservesWSubMStar.trs
#print axioms BetaInstantiationPreservesWSubMStar.of_wsubm
#print axioms BetaInstantiationPreservesWSubM.rfl
#print axioms BetaInstantiationPreservesWSubM.lf1
#print axioms BetaInstantiationPreservesWSubM.lf2
#print axioms BetaInstantiationPreservesWSubM.rgh
#print axioms BetaInstantiationPreservesWSubM.of_reductions
#print axioms BetaInstantiationPreservesMEqRed.top
#print axioms BetaInstantiationPreservesMEqRedStack.top
#print axioms BetaInstantiationPreservesMEqRed.var_zero
#print axioms BetaInstantiationPreservesMEqRedStack.var_zero
#print axioms BetaInstantiationPreservesMEqRedUnderHeadStack.var_zero
#print axioms BetaInstantiationPreservesMEqRed.var_succ
#print axioms BetaInstantiationPreservesMEqRedStack.var_succ
#print axioms BetaInstantiationPreservesMEqRedUnderHeadStack.var_one
#print axioms BetaInstantiationPreservesMEqRedUnderHeadStack.var_succ_succ
#print axioms BetaInstantiationPreservesMEqRedStack.var
#print axioms BetaInstantiationPreservesMEqRedUnderHeadStack.var
#print axioms BetaInstantiationPreservesMEqRed.var_of_stack
#print axioms BetaInstantiationPreservesMEqRedUnderHeadStack.pro
#print axioms BetaInstantiationPreservesMEqRedUnderHeadStack.of_constructors
#print axioms BetaInstantiationPreservesMEqRedUnderHeadsStack
#print axioms BetaInstantiationPreservesMEqRedUnderHeadsStack_universal
#print axioms BetaInstantiationPreservesMEqRedStack_proved
#print axioms BetaInstantiationPreservesMSubRedUnderHeadsStackMSubStar
#print axioms BetaInstantiationPreservesMSubRedUnderHeadsStackMSubStar_universal_of_stack_append
#print axioms BetaInstantiationPreservesMSubRedStackMSubStar_of_stack_append
#print axioms BetaInstantiationPreservesMSubRedMSubStar_of_stack_append
#print axioms MSubStar.lift_through_instantiateBetaPrefix
#print axioms Ctx.subBinds_instantiateBetaPrefix
#print axioms BetaInstantiationPreservesMEqRedStack.of_generic
#print axioms BetaInstantiationPreservesMEqRedUnderHeadsStack.of_stack
#print axioms BetaInstantiationPreservesMEqRedUnderHeadStack.of_generic
#print axioms BetaInstantiationPreservesMSubRed.top
#print axioms BetaInstantiationPreservesMSubRedStack.top
#print axioms BetaInstantiationPreservesMSubRedStack.top_msubstar
#print axioms BetaInstantiationPreservesMSubRedStack.pro_succ
#print axioms BetaInstantiationPreservesMSubRedStack.pro
#print axioms BetaInstantiationPreservesMSubRedStack.pro_msubstar
#print axioms BetaInstantiationPreservesMEqRed.tAp
#print axioms BetaInstantiationPreservesMEqRedStack.tAp
#print axioms BetaInstantiationPreservesMEqRedUnderHeadStack.tAp
#print axioms BetaInstantiationPreservesMEqRedStack.app
#print axioms BetaInstantiationPreservesMEqRedUnderHeadStack.app
#print axioms BetaInstantiationPreservesMSubRed.equ
#print axioms BetaInstantiationPreservesMSubRedStack.equ
#print axioms BetaInstantiationPreservesMSubRedStack.equ_msubstar
#print axioms BetaInstantiationPreservesMSubRed.equ_of_meq
#print axioms BetaInstantiationPreservesMSubRedStack.equ_of_meq
#print axioms BetaInstantiationPreservesMSubRedStack.app
#print axioms BetaInstantiationPreservesMSubRedStack.app_msubstar
#print axioms BetaInstantiationPreservesMSubRedStack.fOp_msubstar
#print axioms BetaInstantiationPreservesMSubRed.fun_msubstar
#print axioms BetaInstantiationPreservesMSubRedStackMSubStar.of_constructors
#print axioms BetaInstantiationPreservesPrevalidExtUnderHead
#print axioms BetaInstantiationPreservesMSubRedUnderHeadMSubStarPayload.of_constructors
#print axioms BetaInstantiationPreservesMSubRedFOpBodyMSubStarPayload.of_under_head
#print axioms BetaInstantiationPreservesMSubRedFunBodyMSubStarPayload.of_under_head
#print axioms BetaInstantiationPreservesMSubRedStackMSubStar.of_under_head_constructors
#print axioms BetaInstantiationPreservesMSubRedUnderHeadMSubStarPayload.of_stack_append_constructors
#print axioms BetaInstantiationPreservesMSubRedUnderHeadMSubStarPayload.of_stack_append_eq_constructors
#print axioms BetaInstantiationPreservesMSubRedStackMSubStar.of_stack_append_under_head_constructors
#print axioms BetaInstantiationPreservesMSubRedStackMSubStar.of_stack_append_under_head_eq_constructors
#print axioms AbsFunctionBoundInversion_of_diagram
#print axioms AbsFunctionBoundInversion_of_chain_diagram
#print axioms AbsFunctionBoundInversionUnderWfCtx_of_chain_shape
#print axioms AbsFunctionBoundInversionUnderWfCtx_of_chain_shape_machine_state
#print axioms AbsFunctionBoundInversion_of_diagram_via_chain
#print axioms AbsFunctionBoundInversion_of_msub
#print axioms AbsFunctionBoundChainShapeWfPayload_of_meq
#print axioms AbsFunctionBoundChainShapeWfUnderWfCtxPayload_of_meq
#print axioms AbsFunctionBoundChainShapeWfUnderWfCtxPayload_of_contextual
#print axioms AbsFunctionBoundChainShapeWfUnderWfCtxPayload_of_machine_state
#print axioms AbsFunctionBoundChainShapeWfClosedPayload_of_contextual
#print axioms AbsFunctionBoundChainShapeWfClosedPayload_of_machine_state
#print axioms MSubStarToWSubMStarPayload.of_steps
#print axioms MSubStackLiftPayload.of_reduction_lifts
#print axioms MSubStackAppendPayload.of_reduction_appends
#print axioms MSubStackLiftPayload.of_append
#print axioms MSubRedStackLiftPayload.of_append
#print axioms MEqRedStackLiftPayload.of_append
#print axioms MEqRedFunStackAppendPayload.of_body_transport
#print axioms MSubRedFunStackAppendPayload.of_body_equ_transport
#print axioms MEqRedStackAppendPayload.of_fun
#print axioms MSubRedStackAppendPayload.of_fun
#print axioms MEqRedStarStackAppendPayload.of_step
#print axioms MSubRedStarStackAppendPayload.of_step
#print axioms MEqRedStarStackLiftPayload.of_append
#print axioms MSubRedStarStackLiftPayload.of_append
#print axioms MEqRedStarStackAppendPayload.of_body_transport
#print axioms MSubRedStarStackAppendPayload.of_body_transports
#print axioms MSubStackAppendPayload.of_body_transports
#print axioms MSubStarStackAppendPayload.of_step
#print axioms MSubStarStackLiftPayload.of_append
#print axioms MSubStarStackAppendPayload.iterate_scoped
#print axioms BetaInstantiationPreservesMSubRedProHeadMSubStarPayload.of_stack_append
#print axioms BetaInstantiationPreservesMSubRedUnderHeadProMSubStarPayload.of_stack_append
#print axioms MSubStarStackAppendPayload.of_body_transports
#print axioms WSubMStarToStackedMSubStarPayload.of_msubstar_stack_append
#print axioms MSubRedStar.stack_replace_from_step_replacement
#print axioms MSubRed.stack_head_replace_from_handlers
#print axioms MEqRed.stack_head_replace_from_handlers
#print axioms MEqRed.stack_head_subtype_replace_from_handlers
#print axioms MEqRed.equ_head_replace_from_handlers
#print axioms MEqRed.replaceAt_equ_from_handlers
#print axioms MSubRed.equ_head_replace_from_handlers
#print axioms MSubRed.replaceAt_equ_from_handlers
#print axioms msubRedStar_equ_head_replace_from_handlers
#print axioms msubRedStar_equ_head_replace_from_handlers_star
#print axioms msubRed_equ_head_replace_from_body_replacements
#print axioms msubRed_equ_under_head_replace_from_body_replacements
#print axioms msubRedStar_equ_head_replace_from_body_replacements
#print axioms msubRedStar_equ_head_replace_from_raw_body_replacements
#print axioms msubRedStar_equ_under_head_replace_from_body_replacements
#print axioms msubRedStar_equ_under_head_replace_from_raw_body_replacements
#print axioms MEqRed.equ_under_head_replace_from_handlers
#print axioms MEqRed.equ_under_sub_head_replace_from_handlers
#print axioms MSubRed.equ_under_head_replace_from_handlers
#print axioms msubRedStar_equ_under_head_replace_from_handlers
#print axioms msubRedStar_equ_under_head_replace_from_handlers_star
#print axioms msub_equ_head_fun_handler_of_body_replacement
#print axioms msub_equ_under_head_fun_handler_of_body_replacement
#print axioms msubRedStar_equ_head_replace_function_from_raw_body_replacements
#print axioms msubRedStar_equ_under_head_replace_function_from_raw_body_replacements
#print axioms MSubRed.equ_under_sub_head_nil_replace_from_handlers
#print axioms MEqRed.equ_under_sub_head_nil_replace_from_split_handlers
#print axioms MSubRed.equ_under_sub_head_nil_replace_from_split_handlers
#print axioms MEqRed.equ_under_sub_head_sub_tail_nil_replace_from_split_handlers
#print axioms MSubRed.equ_under_sub_head_sub_tail_nil_replace_from_split_handlers
#print axioms MEqRed.equ_under_two_heads_replace_from_handlers
#print axioms MSubRed.equ_under_two_heads_replace_from_handlers
#print axioms MEqRed.equ_under_three_heads_replace_from_handlers
#print axioms MSubRed.equ_under_three_heads_replace_from_handlers
#print axioms meqRed_equ_under_three_heads_replace_from_handlers
#print axioms msubRed_equ_under_three_heads_replace_from_handlers
#print axioms msubRed_equ_under_three_heads_replace_from_replacements
#print axioms msubRedStar_equ_under_three_heads_replace_from_handlers
#print axioms msubRedStar_equ_under_three_heads_replace_from_handlers_star
#print axioms msubRedStar_equ_under_three_heads_replace_from_replacements
#print axioms msubRedStar_equ_under_three_heads_replace_from_raw_body_replacements
#print axioms msubRedStar_equ_under_three_heads_replace_function_from_raw_body_replacements
#print axioms meqRed_equ_under_sub_head_sub_tail_nil_replace_from_handlers
#print axioms meqRed_equ_under_sub_head_sub_tail_nil_replace_from_replacements
#print axioms meqRedStar_equ_under_sub_head_sub_tail_nil_replace_from_handlers
#print axioms meqRedStar_equ_under_sub_head_sub_tail_nil_replace_from_replacements
#print axioms meqRed_replaceAt_equ_from_handlers
#print axioms meqRed_replaceAt_equ_from_replacements
#print axioms meqRedStar_replaceAt_equ_from_replacements
#print axioms meqRedStar_replaceAt_equ_function_from_replacements
#print axioms msubRed_equ_under_sub_head_sub_tail_nil_replace_from_handlers
#print axioms msubRed_equ_under_sub_head_sub_tail_nil_replace_from_replacements
#print axioms msubRed_equ_under_sub_head_sub_tail_nil_replace_from_body_replacements
#print axioms msubRedStar_equ_under_sub_head_sub_tail_nil_replace_from_raw_handlers
#print axioms msubRedStar_equ_under_sub_head_sub_tail_nil_replace_from_raw_handlers_star
#print axioms msubRedStar_equ_under_sub_head_sub_tail_nil_replace_from_handlers
#print axioms msubRedStar_equ_under_sub_head_sub_tail_nil_replace_from_replacements
#print axioms msubRedStar_equ_under_sub_head_sub_tail_nil_replace_from_body_replacements
#print axioms msubRed_replaceAt_equ_from_handlers
#print axioms msubRed_replaceAt_equ_from_replacements
#print axioms msubRedStar_replaceAt_equ_from_replacements
#print axioms msubRedStar_replaceAt_equ_function_from_replacements
#print axioms msubRedStar_equ_under_two_heads_replace_from_replacements
#print axioms msubRedStar_equ_under_two_heads_replace_function_from_replacements
#print axioms msubRedStar_equ_under_three_heads_replace_function_from_replacements
#print axioms msub_equ_under_two_heads_app_handler_of_operator_replacement
#print axioms msub_equ_under_two_heads_fun_handler_of_raw_replacements
#print axioms msub_equ_under_two_heads_fop_handler_of_body_replacement
#print axioms msubRedStar_equ_under_two_heads_replace_from_handlers
#print axioms msubRedStar_equ_under_two_heads_replace_from_handlers_star
#print axioms msubRedStar_equ_under_two_heads_replace_from_raw_body_replacements
#print axioms msubRedStar_equ_under_two_heads_replace_function_from_raw_body_replacements
#print axioms msubRed_equ_under_two_heads_replace_from_replacements
#print axioms MEqRed.equ_under_two_sub_heads_replace_from_handlers
#print axioms MEqRed.equ_under_two_sub_heads_nil_replace_from_handlers
#print axioms MEqRed.equ_under_two_sub_heads_nil_replace_from_split_handlers
#print axioms MEqRed.equ_under_two_sub_heads_sub_tail_nil_replace_from_split_handlers
#print axioms MEqRed.equ_under_three_sub_heads_sub_tail_nil_replace_from_split_handlers
#print axioms MSubRed.pro_equ_under_two_heads_replace
#print axioms MSubRed.pro_replaceAt_equ
#print axioms MSubRed.equ_under_two_sub_heads_nil_replace_from_handlers
#print axioms MSubRed.equ_under_two_sub_heads_nil_replace_from_split_handlers
#print axioms MSubRed.equ_under_two_sub_heads_sub_tail_nil_replace_from_split_handlers
#print axioms MSubRed.equ_under_three_sub_heads_sub_tail_nil_replace_from_split_handlers
#print axioms msub_equ_under_two_heads_old_bound_to_new_bvar2
#print axioms msub_equ_under_two_heads_new_bvar2_to_old_bound
#print axioms msubStar_equ_under_two_heads_new_bvar2_to_replaced_residual
#print axioms meq_equ_under_two_heads_pro_two_handler_of_replacement
#print axioms msub_equ_under_three_heads_old_bound_to_new_bvar3
#print axioms msub_equ_under_three_heads_new_bvar3_to_old_bound
#print axioms msubStar_equ_under_three_heads_new_bvar3_to_replaced_residual
#print axioms meq_equ_under_three_heads_pro_three_handler_of_replacement
#print axioms MSubRed.pro_equ_under_three_heads_replace
#print axioms meq_equ_under_two_heads_pro_zero_handler_of_replacement
#print axioms meq_equ_under_two_heads_pro_one_handler_of_replacement
#print axioms meq_equ_under_two_heads_pro_tail_handler_of_replacement
#print axioms meq_equ_under_three_heads_pro_zero_handler_of_replacement
#print axioms meq_equ_under_three_heads_pro_one_handler_of_replacement
#print axioms meq_equ_under_three_heads_pro_two_handler_of_replacement
#print axioms meq_equ_under_three_heads_pro_tail_handler_of_replacement
#print axioms meqRed_equ_under_three_heads_replace_with_pro_from_replacements
#print axioms meqRedStar_equ_under_three_heads_replace_with_pro_from_replacements
#print axioms meqRedStar_equ_under_three_heads_replace_with_pro_function_from_replacements
#print axioms msubRedStar_equ_under_three_heads_replace_with_pro_from_replacements
#print axioms msubRedStar_equ_under_three_heads_replace_with_pro_function_from_replacements
#print axioms meqRed_equ_under_two_heads_replace_with_pro_from_replacements
#print axioms meqRedStar_equ_under_two_heads_replace_with_pro_from_replacements
#print axioms meqRedStar_equ_under_two_heads_replace_with_pro_function_from_replacements
#print axioms msubRedStar_equ_under_two_heads_replace_with_pro_from_replacements
#print axioms msubRedStar_equ_under_two_heads_replace_with_pro_function_from_replacements
#print axioms MEqRed.sub_head_replace
#print axioms MEqRed.sub_head_replace_two_step
#print axioms MEqRed.sub_to_equ_head_replace
#print axioms MEqRed.replaceAt_sub_to_equ
#print axioms MEqRedStar.sub_head_replace
#print axioms MEqRedStar.sub_head_replace_star
#print axioms MSubRedStar.equ_sub_head_replace
#print axioms MSubRedStar.of_meqStar_sub_head_replace_star
#print axioms MSubRedStarStackLiftPayload.of_step
#print axioms MEqRedStarStackLiftPayload.of_step
#print axioms MSubStarStackLiftPayload.of_step
#print axioms meqRedStar_equ_head_stack_lift_from_step_lift
#print axioms meqRedStar_equ_head_stack_lift_function_from_step_lift
#print axioms msubRedStar_equ_head_stack_lift_from_step_lift
#print axioms msubRedStar_equ_head_stack_lift_function_from_step_lift
#print axioms msubRedStar_equ_head_stack_lift_from_step_star_lift
#print axioms msubRedStar_equ_head_stack_lift_function_from_step_star_lift
#print axioms msubRed_equ_head_stack_lift_from_replacements
#print axioms msubRedStar_equ_head_stack_lift_from_replacements
#print axioms msubRedStar_equ_head_stack_lift_function_from_replacements
#print axioms msubStar_equ_head_stack_lift_from_step_msub_lift
#print axioms msubStar_equ_head_stack_lift_function_from_step_msub_lift
#print axioms msub_equ_head_stack_lift_from_replacements
#print axioms msubStar_equ_head_stack_lift_from_replacements
#print axioms msubStar_equ_head_stack_lift_function_from_replacements
#print axioms WSubMStarToStackedMSubStarPayload.of_msubstar_stack_lift
#print axioms MSubStackLiftPayload.of_body_transports
#print axioms WSubMStarToStackedMSubStarPayload.of_body_transports
#print axioms WSubMStarAppOperatorPayload.of_stacked_msubstar_bridge
#print axioms WSubMStarAppOperatorPayload.of_stacked_msubstar_append_bridge
#print axioms WSubMStarAppOperatorPayload.of_body_transports_and_steps
#print axioms WfMachineStateControlLeftPayload.of_app_operator
#print axioms WfMachineStateControlLeftPayload.of_msubstar_stack_append
#print axioms WfMachineStateControlLeftPayload.of_body_transports_and_steps
#print axioms MEqRedMachineStackHeadReplacePayload.of_msubstar_stack_append
#print axioms MEqRedProAnnotationMachineStatePayload.of_msubstar_stack_append
#print axioms MEqRedPreservesWfMachineState.of_components
#print axioms MEqRedPreservesWfMachineState.of_components_pro_annotation
#print axioms MEqRedPreservesWfMachineState.of_reduced_components
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append
#print axioms MEqRedPreservesWfMachineState.of_body_transports
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_typed_fop
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_typed_fop_exact_tail
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_typed_fop_cons_tail
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_typed_fop_tail_step
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_typed_fop_tail_step_cons
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_typed_fop_target_app_tail_step
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_typed_fop_operator_tail_step
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_typed_fop_machine_operator_tail_step
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_beta_target_typed_fop_target_app_tail_step
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_beta_target_typed_fop_operator_tail_step
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_beta_target_typed_fop_machine_operator_tail_step
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_beta_target_typed_fop_target_app_machine_tail
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_beta_target_typed_fop_operator_machine_tail
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_beta_target_typed_fop_machine_operator_machine_tail
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_beta_target_typed_fop_target_app_machine_tail_cons
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_contextual_beta_typed_fop_target_app_machine_tail_cons
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_beta_target_typed_fop_operator_machine_tail_cons
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_contextual_beta_typed_fop_operator_machine_tail_cons
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_beta_target_typed_fop_machine_operator_machine_tail_cons
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_contextual_beta_typed_fop_machine_operator_machine_tail_cons
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_split_beta_typed_fop_target_app_machine_tail_cons
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_split_beta_typed_fop_operator_machine_tail_cons
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_split_beta_typed_fop_machine_operator_machine_tail_cons
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_direct_split_beta_typed_fop_target_app_machine_tail_cons
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_direct_split_beta_typed_fop_operator_machine_tail
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_direct_split_beta_typed_fop_machine_operator_machine_tail
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_direct_split_beta_fop_target_app_machine_tail_cons
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_direct_split_beta_fop_operator_machine_tail
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_direct_split_beta_fop_machine_operator_machine_tail
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_direct_split_beta_typed_fop_target_app_machine_tail_cons_sub_replace
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_direct_split_beta_fop_target_app_machine_tail_cons_sub_replace
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_direct_split_beta_typed_fop_operator_machine_tail_sub_replace
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_direct_split_beta_typed_fop_machine_operator_machine_tail_sub_replace
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_direct_split_beta_fop_operator_machine_tail_sub_replace
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_direct_split_beta_fop_machine_operator_machine_tail_sub_replace
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_direct_split_beta_typed_fop_target_app_machine_tail_cons_contextual
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_direct_split_beta_fop_target_app_machine_tail_cons_contextual
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_direct_split_beta_typed_fop_operator_machine_tail_contextual
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_direct_split_beta_typed_fop_machine_operator_machine_tail_contextual
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_direct_split_beta_fop_operator_machine_tail_contextual
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_direct_split_beta_fop_machine_operator_machine_tail_contextual
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_direct_split_beta_chain_shape_wfctx_target_app_machine_tail_cons
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_direct_split_beta_chain_shape_wfctx_factored_target_app_machine_tail_cons
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_direct_split_beta_chain_shape_wfctx_factored_operator_machine_tail
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_direct_split_beta_chain_shape_wfctx_factored_machine_operator_machine_tail
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_direct_split_beta_chain_shape_wfctx_factored_head_kind_target_app_machine_tail_cons
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_direct_split_beta_chain_shape_wfctx_factored_head_kind_operator_machine_tail
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_direct_split_beta_chain_shape_wfctx_factored_head_kind_machine_operator_machine_tail
#print axioms MEqRedPreservesWfMachineState.of_body_transports_and_direct_split_beta_chain_shape_wfctx_target_app_machine_tail_cons
#print axioms MEqRedPreservesWfMachineState.of_body_transports_and_direct_split_beta_chain_shape_wfctx_factored_target_app_machine_tail_cons
#print axioms MEqRedPreservesWfMachineState.of_body_transports_and_direct_split_beta_chain_shape_wfctx_factored_operator_machine_tail
#print axioms MEqRedPreservesWfMachineState.of_body_transports_and_direct_split_beta_chain_shape_wfctx_factored_machine_operator_machine_tail
#print axioms MEqRedPreservesWfMachineState.of_body_transports_and_direct_split_beta_chain_shape_wfctx_factored_head_kind_target_app_machine_tail_cons
#print axioms MEqRedPreservesWfMachineState.of_body_transports_and_direct_split_beta_chain_shape_wfctx_factored_head_kind_operator_machine_tail
#print axioms MEqRedPreservesWfMachineState.of_body_transports_and_direct_split_beta_chain_shape_wfctx_factored_head_kind_machine_operator_machine_tail
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_no_empty
#print axioms MEqRedPreservesWfMachineState.of_body_transports_no_empty
#print axioms MEqRedPreservesWfMachineState.of_control_left_no_empty_and_typed_fop_target_app_tail_step
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_no_empty_and_typed_fop_target_app_tail_step
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_no_empty_and_typed_fop_operator_tail_step
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_no_empty_and_typed_fop_machine_operator_tail_step
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_no_empty_and_beta_target_typed_fop_target_app_tail_step
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_no_empty_and_beta_target_typed_fop_operator_tail_step
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_no_empty_and_beta_target_typed_fop_machine_operator_tail_step
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_no_empty_and_beta_target_typed_fop_target_app_machine_tail
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_no_empty_and_beta_target_typed_fop_operator_machine_tail
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_no_empty_and_beta_target_typed_fop_machine_operator_machine_tail
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_no_empty_and_beta_target_typed_fop_target_app_machine_tail_cons
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_no_empty_and_contextual_beta_typed_fop_target_app_machine_tail_cons
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_no_empty_and_beta_target_typed_fop_operator_machine_tail_cons
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_no_empty_and_contextual_beta_typed_fop_operator_machine_tail_cons
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_no_empty_and_beta_target_typed_fop_machine_operator_machine_tail_cons
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_no_empty_and_contextual_beta_typed_fop_machine_operator_machine_tail_cons
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_no_empty_and_split_beta_typed_fop_target_app_machine_tail_cons
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_no_empty_and_split_beta_typed_fop_operator_machine_tail_cons
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_no_empty_and_split_beta_typed_fop_machine_operator_machine_tail_cons
#print axioms MEqRedPreservesWfMachineState.of_control_left_no_empty_and_direct_split_beta_typed_fop_target_app_machine_tail_cons
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_no_empty_and_direct_split_beta_typed_fop_target_app_machine_tail_cons
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_no_empty_and_direct_split_beta_typed_fop_operator_machine_tail
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_no_empty_and_direct_split_beta_typed_fop_machine_operator_machine_tail
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_no_empty_and_direct_split_beta_fop_target_app_machine_tail_cons
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_no_empty_and_direct_split_beta_fop_operator_machine_tail
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_no_empty_and_direct_split_beta_fop_machine_operator_machine_tail
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_no_empty_and_direct_split_beta_typed_fop_target_app_machine_tail_cons_sub_replace
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_no_empty_and_direct_split_beta_typed_fop_target_app_machine_tail_cons_direct_sub_payloads
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_no_empty_and_direct_split_beta_typed_fop_target_app_machine_tail_cons_immediate_sub_payloads_and_under
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_no_empty_and_direct_split_beta_fop_target_app_machine_tail_cons_sub_replace
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_no_empty_and_direct_split_beta_fop_target_app_machine_tail_cons_direct_sub_payloads
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_no_empty_and_direct_split_beta_fop_target_app_machine_tail_cons_immediate_sub_payloads_and_under
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_no_empty_and_direct_split_beta_typed_fop_operator_machine_tail_sub_replace
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_no_empty_and_direct_split_beta_typed_fop_operator_machine_tail_direct_sub_payloads
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_no_empty_and_direct_split_beta_typed_fop_operator_machine_tail_immediate_sub_payloads_and_under
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_no_empty_and_direct_split_beta_typed_fop_machine_operator_machine_tail_sub_replace
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_no_empty_and_direct_split_beta_typed_fop_machine_operator_machine_tail_direct_sub_payloads
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_no_empty_and_direct_split_beta_typed_fop_machine_operator_machine_tail_immediate_sub_payloads_and_under
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_no_empty_and_direct_split_beta_fop_operator_machine_tail_sub_replace
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_no_empty_and_direct_split_beta_fop_operator_machine_tail_direct_sub_payloads
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_no_empty_and_direct_split_beta_fop_operator_machine_tail_immediate_sub_payloads_and_under
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_no_empty_and_direct_split_beta_fop_machine_operator_machine_tail_sub_replace
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_no_empty_and_direct_split_beta_fop_machine_operator_machine_tail_direct_sub_payloads
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_no_empty_and_direct_split_beta_fop_machine_operator_machine_tail_immediate_sub_payloads_and_under
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_no_empty_and_direct_split_beta_typed_fop_target_app_machine_tail_cons_contextual
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_no_empty_and_direct_split_beta_fop_target_app_machine_tail_cons_contextual
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_no_empty_and_direct_split_beta_typed_fop_operator_machine_tail_contextual
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_no_empty_and_direct_split_beta_typed_fop_machine_operator_machine_tail_contextual
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_no_empty_and_direct_split_beta_fop_operator_machine_tail_contextual
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_no_empty_and_direct_split_beta_fop_machine_operator_machine_tail_contextual
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_no_empty_and_direct_split_beta_chain_shape_wfctx_target_app_machine_tail_cons
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_no_empty_and_direct_split_beta_chain_shape_wfctx_factored_target_app_machine_tail_cons
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_no_empty_and_direct_split_beta_chain_shape_wfctx_factored_operator_machine_tail
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_no_empty_and_direct_split_beta_chain_shape_wfctx_factored_machine_operator_machine_tail
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_no_empty_and_direct_split_beta_chain_shape_wfctx_factored_head_kind_target_app_machine_tail_cons
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_no_empty_and_direct_split_beta_chain_shape_wfctx_factored_head_kind_operator_machine_tail
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_no_empty_and_direct_split_beta_chain_shape_wfctx_factored_head_kind_machine_operator_machine_tail
#print axioms MEqRedPreservesWfMachineState.of_body_transports_no_empty_and_direct_split_beta_chain_shape_wfctx_target_app_machine_tail_cons
#print axioms MEqRedPreservesWfMachineState.of_body_transports_no_empty_and_direct_split_beta_chain_shape_wfctx_factored_target_app_machine_tail_cons
#print axioms MEqRedPreservesWfMachineState.of_body_transports_no_empty_and_direct_split_beta_chain_shape_wfctx_factored_operator_machine_tail
#print axioms MEqRedPreservesWfMachineState.of_body_transports_no_empty_and_direct_split_beta_chain_shape_wfctx_factored_machine_operator_machine_tail
#print axioms MEqRedPreservesWfMachineState.of_body_transports_no_empty_and_direct_split_beta_chain_shape_wfctx_factored_head_kind_target_app_machine_tail_cons
#print axioms MEqRedPreservesWfMachineState.of_body_transports_no_empty_and_direct_split_beta_chain_shape_wfctx_factored_head_kind_operator_machine_tail
#print axioms MEqRedPreservesWfMachineState.of_body_transports_no_empty_and_direct_split_beta_chain_shape_wfctx_factored_head_kind_machine_operator_machine_tail
#print axioms MEqRedPreservesWfMachineState.of_body_transports_no_empty_and_direct_split_beta_typed_fop_target_app_machine_tail_cons_direct_sub_payloads
#print axioms MEqRedPreservesWfMachineState.of_body_transports_no_empty_and_direct_split_beta_typed_fop_target_app_machine_tail_cons_immediate_sub_payloads_and_under
#print axioms MEqRedPreservesWfMachineState.of_body_transports_no_empty_and_direct_split_beta_fop_target_app_machine_tail_cons_direct_sub_payloads
#print axioms MEqRedPreservesWfMachineState.of_body_transports_no_empty_and_direct_split_beta_fop_target_app_machine_tail_cons_immediate_sub_payloads_and_under
#print axioms MEqRedPreservesWfMachineState.of_body_transports_no_empty_and_direct_split_beta_typed_fop_operator_machine_tail_direct_sub_payloads
#print axioms MEqRedPreservesWfMachineState.of_body_transports_no_empty_and_direct_split_beta_typed_fop_operator_machine_tail_immediate_sub_payloads_and_under
#print axioms MEqRedPreservesWfMachineState.of_body_transports_no_empty_and_direct_split_beta_typed_fop_machine_operator_machine_tail_direct_sub_payloads
#print axioms MEqRedPreservesWfMachineState.of_body_transports_no_empty_and_direct_split_beta_typed_fop_machine_operator_machine_tail_immediate_sub_payloads_and_under
#print axioms MEqRedPreservesWfMachineState.of_body_transports_no_empty_and_direct_split_beta_fop_operator_machine_tail_direct_sub_payloads
#print axioms MEqRedPreservesWfMachineState.of_body_transports_no_empty_and_direct_split_beta_fop_operator_machine_tail_immediate_sub_payloads_and_under
#print axioms MEqRedPreservesWfMachineState.of_body_transports_no_empty_and_direct_split_beta_fop_machine_operator_machine_tail_direct_sub_payloads
#print axioms MEqRedPreservesWfMachineState.of_body_transports_no_empty_and_direct_split_beta_fop_machine_operator_machine_tail_immediate_sub_payloads_and_under
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_direct_split_beta_typed_fop_target_app_machine_tail_cons_direct_sub_payloads
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_direct_split_beta_typed_fop_target_app_machine_tail_cons_immediate_sub_payloads_and_under
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_direct_split_beta_fop_target_app_machine_tail_cons_direct_sub_payloads
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_direct_split_beta_fop_target_app_machine_tail_cons_immediate_sub_payloads_and_under
#print axioms MEqRedPreservesWfMachineState.of_body_transports_and_direct_split_beta_typed_fop_target_app_machine_tail_cons_direct_sub_payloads
#print axioms MEqRedPreservesWfMachineState.of_body_transports_and_direct_split_beta_typed_fop_target_app_machine_tail_cons_immediate_sub_payloads_and_under
#print axioms MEqRedPreservesWfMachineState.of_body_transports_and_direct_split_beta_fop_target_app_machine_tail_cons_direct_sub_payloads
#print axioms MEqRedPreservesWfMachineState.of_body_transports_and_direct_split_beta_fop_target_app_machine_tail_cons_immediate_sub_payloads_and_under
#print axioms MEqRedPreservesWfMachineState.of_body_transports_and_direct_split_beta_typed_fop_operator_machine_tail_direct_sub_payloads
#print axioms MEqRedPreservesWfMachineState.of_body_transports_and_direct_split_beta_typed_fop_operator_machine_tail_immediate_sub_payloads_and_under
#print axioms MEqRedPreservesWfMachineState.of_body_transports_and_direct_split_beta_typed_fop_machine_operator_machine_tail_direct_sub_payloads
#print axioms MEqRedPreservesWfMachineState.of_body_transports_and_direct_split_beta_typed_fop_machine_operator_machine_tail_immediate_sub_payloads_and_under
#print axioms MEqRedPreservesWfMachineState.of_body_transports_and_direct_split_beta_fop_operator_machine_tail_direct_sub_payloads
#print axioms MEqRedPreservesWfMachineState.of_body_transports_and_direct_split_beta_fop_operator_machine_tail_immediate_sub_payloads_and_under
#print axioms MEqRedPreservesWfMachineState.of_body_transports_and_direct_split_beta_fop_machine_operator_machine_tail_direct_sub_payloads
#print axioms MEqRedPreservesWfMachineState.of_body_transports_and_direct_split_beta_fop_machine_operator_machine_tail_immediate_sub_payloads_and_under
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_direct_split_beta_typed_fop_operator_machine_tail_direct_sub_payloads
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_direct_split_beta_typed_fop_operator_machine_tail_immediate_sub_payloads_and_under
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_direct_split_beta_typed_fop_machine_operator_machine_tail_direct_sub_payloads
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_direct_split_beta_typed_fop_machine_operator_machine_tail_immediate_sub_payloads_and_under
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_direct_split_beta_fop_operator_machine_tail_direct_sub_payloads
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_direct_split_beta_fop_operator_machine_tail_immediate_sub_payloads_and_under
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_direct_split_beta_fop_machine_operator_machine_tail_direct_sub_payloads
#print axioms MEqRedPreservesWfMachineState.of_msubstar_stack_append_and_direct_split_beta_fop_machine_operator_machine_tail_immediate_sub_payloads_and_under
#print axioms WfMSubHeadReplaceOfNewWf.of_direct_payloads
#print axioms WfMSubUnderHeadReplaceOfNewWf.of_direct_payloads
#print axioms WfMSubHeadReplaceDirectPayloads.of_immediate_and_under
#print axioms WfMSubHeadReplaceOfNewWf.of_immediate_payloads_and_under
#print axioms WfMSubHeadReplaceOfNewWf_partial_proved
#print axioms WfMSubHeadReplaceOfNewWf.top_cell
#print axioms WfMSubHeadReplaceOfNewWf.var_cell
#print axioms WfMSubHeadReplaceOfNewWf.dispatch
#print axioms MEqRedFunBodyReplacePayload.of_direct_sub_payloads
#print axioms MEqRedFunBodyReplacePayload.of_immediate_sub_payloads_and_under
#print axioms MEqRed.fun_preservesWfM_of_direct_sub_payloads
#print axioms MEqRed.fun_preservesWfM_of_immediate_sub_payloads_and_under
#print axioms MEqRedPreservesWfMContextual.of_components_and_direct_sub_payloads
#print axioms MEqRedPreservesWfMContextual.of_components_and_immediate_sub_payloads_and_under
#print axioms MEqRedPreservesWfMContextual.of_components_no_beta_and_direct_sub_payloads
#print axioms MEqRedPreservesWfMContextual.of_components_no_beta_and_immediate_sub_payloads_and_under
#print axioms MEqRedPreservesWfMContextual.of_components_no_beta_under_wfctx_inv_and_direct_sub_payloads
#print axioms MEqRedPreservesWfMContextual.of_components_no_beta_under_wfctx_inv_and_immediate_sub_payloads_and_under
#print axioms MEqRedPreservesWfMContextual.of_components_no_beta_under_wfctx_inv_and_direct_sub_payloads_and_head_transports
#print axioms MEqRedPreservesWfMContextual.of_components_no_beta_under_wfctx_inv_and_immediate_sub_payloads_and_under_and_head_transports
#print axioms MEqRedPreservesWfMContextual.of_factored_components_no_beta_and_direct_sub_payloads
#print axioms MEqRedPreservesWfMContextual.of_factored_components_no_beta_and_immediate_sub_payloads_and_under
#print axioms MEqRedPreservesWfMContextual.of_chain_diagram_no_beta_and_direct_sub_payloads
#print axioms MEqRedPreservesWfMContextual.of_chain_diagram_no_beta_and_immediate_sub_payloads_and_under
#print axioms MEqRedPreservesWfMContextual.of_chain_shape_no_beta_and_direct_sub_payloads
#print axioms MEqRedPreservesWfMContextual.of_chain_shape_no_beta_and_immediate_sub_payloads_and_under
#print axioms MEqRedPreservesWfMContextual.of_chain_shape_wfctx_no_beta_and_direct_sub_payloads
#print axioms MEqRedPreservesWfMContextual.of_chain_shape_wfctx_no_beta_and_immediate_sub_payloads_and_under
#print axioms MEqRedPreservesWfMContextual.of_chain_shape_wfctx_no_beta_and_direct_sub_payloads_and_head_transports
#print axioms MEqRedPreservesWfMContextual.of_chain_shape_wfctx_no_beta_and_immediate_sub_payloads_and_under_and_head_transports
#print axioms MEqRedPreservesWfMContextual.of_chain_shape_wfctx_no_beta_and_direct_sub_payloads_and_head_kind_transport
#print axioms MEqRedPreservesWfMContextual.of_chain_shape_wfctx_no_beta_and_immediate_sub_payloads_and_under_and_head_kind_transport
#print axioms MEqRedPreservesWfMContextual.of_chain_shape_wfctx_left_factored_no_beta_and_direct_sub_payloads
#print axioms MEqRedPreservesWfMContextual.of_chain_shape_wfctx_left_factored_no_beta_and_immediate_sub_payloads_and_under
#print axioms MEqRedPreservesWfMContextual.of_chain_shape_wfctx_factored_no_beta_and_direct_sub_payloads_and_head_transports
#print axioms MEqRedPreservesWfMContextual.of_chain_shape_wfctx_factored_no_beta_and_immediate_sub_payloads_and_under_and_head_transports
#print axioms MEqRedPreservesWfMContextual.of_chain_shape_wfctx_factored_no_beta_and_direct_sub_payloads
#print axioms MEqRedPreservesWfMContextual.of_chain_shape_wfctx_factored_no_beta_and_immediate_sub_payloads_and_under
#print axioms MEqRedPreservesWfMContextual.of_chain_shape_machine_state_no_beta_and_direct_sub_payloads_and_head_transports
#print axioms MEqRedPreservesWfMContextual.of_chain_shape_machine_state_no_beta_and_immediate_sub_payloads_and_under_and_head_transports
#print axioms MEqRedPreservesWfMContextual.of_chain_shape_machine_state_factored_no_beta_and_direct_sub_payloads_and_head_transports
#print axioms MEqRedPreservesWfMContextual.of_chain_shape_machine_state_factored_no_beta_and_immediate_sub_payloads_and_under_and_head_transports
#print axioms StepBetaPreservesWfM_of
#print axioms StepBetaPreservesWfMUnderWfCtx_of
#print axioms StepBetaPreservesWfM_of_diagram
#print axioms StepBetaPreservesWfM_of_chain_diagram
#print axioms StepBetaPreservesWfM_of_chain_shape
#print axioms StepPreservesWfM_of
#print axioms StepPreservesWfMUnderWfCtx_of_new_wf
#print axioms StepPreservesWfM_of_new_wf
#print axioms StepPreservesWfM_of_components
#print axioms StepPreservesWfMUnderWfCtx_of_components
#print axioms StepPreservesWfM_of_diagram_components
#print axioms StepPreservesWfM_of_chain_diagram_components
#print axioms StepPreservesWfM_of_chain_shape_components
#print axioms StepPreservesWfM_of_chain_shape_meq_components
#print axioms StepPreservesWfM_of_components_and_direct_sub_replace
#print axioms StepPreservesWfMUnderWfCtx_of_components_and_direct_sub_replace
#print axioms StepPreservesWfM_of_components_and_immediate_sub_replace_and_under
#print axioms StepPreservesWfMUnderWfCtx_of_components_and_immediate_sub_replace_and_under
#print axioms StepPreservesWfM_of_diagram_components_and_direct_sub_replace
#print axioms StepPreservesWfM_of_diagram_components_and_immediate_sub_replace_and_under
#print axioms StepPreservesWfM_of_chain_diagram_components_and_direct_sub_replace
#print axioms StepPreservesWfM_of_chain_diagram_components_and_immediate_sub_replace_and_under
#print axioms StepPreservesWfM_of_chain_shape_components_and_direct_sub_replace
#print axioms StepPreservesWfM_of_chain_shape_components_and_immediate_sub_replace_and_under
#print axioms StepPreservesWfM_of_chain_shape_meq_components_and_direct_sub_replace
#print axioms StepPreservesWfM_of_chain_shape_meq_components_and_immediate_sub_replace_and_under
#print axioms Theorem_5_DeBruijn_Preservation_of
#print axioms Theorem_5_DeBruijn_ClosedPreservation_of
#print axioms Theorem_5_DeBruijn_Preservation_of_components
#print axioms Theorem_5_DeBruijn_ClosedPreservation_of_components
#print axioms Theorem_5_DeBruijn_Preservation_of_components_and_direct_sub_replace
#print axioms Theorem_5_DeBruijn_ClosedPreservation_of_components_and_direct_sub_replace
#print axioms Theorem_5_DeBruijn_Preservation_of_components_and_immediate_sub_replace_and_under
#print axioms Theorem_5_DeBruijn_ClosedPreservation_of_components_and_immediate_sub_replace_and_under
#print axioms Theorem_5_DeBruijn_Preservation_of_diagram_components
#print axioms Theorem_5_DeBruijn_ClosedPreservation_of_diagram_components
#print axioms Theorem_5_DeBruijn_Preservation_of_diagram_components_and_direct_sub_replace
#print axioms Theorem_5_DeBruijn_ClosedPreservation_of_diagram_components_and_direct_sub_replace
#print axioms Theorem_5_DeBruijn_Preservation_of_diagram_components_and_immediate_sub_replace_and_under
#print axioms Theorem_5_DeBruijn_ClosedPreservation_of_diagram_components_and_immediate_sub_replace_and_under
#print axioms Theorem_5_DeBruijn_Preservation_of_chain_diagram_components
#print axioms Theorem_5_DeBruijn_ClosedPreservation_of_chain_diagram_components
#print axioms Theorem_5_DeBruijn_Preservation_of_chain_diagram_components_and_direct_sub_replace
#print axioms Theorem_5_DeBruijn_ClosedPreservation_of_chain_diagram_components_and_direct_sub_replace
#print axioms Theorem_5_DeBruijn_Preservation_of_chain_diagram_components_and_immediate_sub_replace_and_under
#print axioms Theorem_5_DeBruijn_ClosedPreservation_of_chain_diagram_components_and_immediate_sub_replace_and_under
#print axioms Theorem_5_DeBruijn_Preservation_of_chain_shape_components
#print axioms Theorem_5_DeBruijn_ClosedPreservation_of_chain_shape_components
#print axioms Theorem_5_DeBruijn_Preservation_of_chain_shape_components_and_direct_sub_replace
#print axioms Theorem_5_DeBruijn_ClosedPreservation_of_chain_shape_components_and_direct_sub_replace
#print axioms Theorem_5_DeBruijn_Preservation_of_chain_shape_components_and_immediate_sub_replace_and_under
#print axioms Theorem_5_DeBruijn_ClosedPreservation_of_chain_shape_components_and_immediate_sub_replace_and_under
#print axioms Theorem_5_DeBruijn_Preservation_of_chain_shape_meq_components
#print axioms Theorem_5_DeBruijn_ClosedPreservation_of_chain_shape_meq_components
#print axioms Theorem_5_DeBruijn_Preservation_of_chain_shape_meq_components_and_direct_sub_replace
#print axioms Theorem_5_DeBruijn_ClosedPreservation_of_chain_shape_meq_components_and_direct_sub_replace
#print axioms Theorem_5_DeBruijn_Preservation_of_chain_shape_meq_components_and_immediate_sub_replace_and_under
#print axioms Theorem_5_DeBruijn_ClosedPreservation_of_chain_shape_meq_components_and_immediate_sub_replace_and_under
#print axioms Theorem_5_DeBruijn_Preservation_of_comm_meq_components_and_direct_sub_replace
#print axioms Theorem_5_DeBruijn_ClosedPreservation_of_comm_meq_components_and_direct_sub_replace
#print axioms Theorem_5_DeBruijn_Preservation_of_comm_meq_components_and_immediate_sub_replace_and_under
#print axioms Theorem_5_DeBruijn_ClosedPreservation_of_comm_meq_components_and_immediate_sub_replace_and_under
#print axioms Theorem_5_DeBruijn_Preservation_under_wfctx_of
#print axioms Theorem_5_DeBruijn_ClosedPreservation_under_wfctx_of
#print axioms Theorem_5_DeBruijn_Preservation_under_wfctx_of_comm_machine_components_and_direct_sub_replace
#print axioms Theorem_5_DeBruijn_ClosedPreservation_under_wfctx_of_comm_machine_components_and_direct_sub_replace
#print axioms Theorem_5_DeBruijn_Preservation_under_wfctx_of_comm_machine_components_and_immediate_sub_replace_and_under
#print axioms Theorem_5_DeBruijn_ClosedPreservation_under_wfctx_of_comm_machine_components_and_immediate_sub_replace_and_under
#print axioms Theorem_5_DeBruijn_Preservation_under_wfctx_of_comm_body_transports_no_empty_factored_machine_operator_and_direct_sub_replace
#print axioms Theorem_5_DeBruijn_ClosedPreservation_under_wfctx_of_comm_body_transports_no_empty_factored_machine_operator_and_direct_sub_replace
#print axioms Theorem_5_DeBruijn_Preservation_under_wfctx_of_comm_body_transports_no_empty_factored_machine_operator_and_immediate_sub_replace_and_under
#print axioms Theorem_5_DeBruijn_ClosedPreservation_under_wfctx_of_comm_body_transports_no_empty_factored_machine_operator_and_immediate_sub_replace_and_under

-- Audit: fused kind-narrowing β-substitution. The `bet × bet` diamond
-- cell consumes this surface (composed with body and argument diamond
-- closures) to bridge β-fires that disagree on the post-step argument.
-- The fully asymmetric LHS/RHS form is structurally infeasible as a
-- single `MEqRed` step (see the file docstring for the `Me-FOp`/`Me-Pro`
-- conflict analysis); this kind-narrowed surface delivers the closest
-- provable single-step bridge.
#print axioms MEqRedFusedKindNarrowedBetaSubstStack_proved
#print axioms MEqRedFusedKindNarrowedBetaSubstUnderHeadsStack_universal

-- Audit: argument-transport lemma (Path 3, restricted form). Companion to
-- the fused kind-narrowing β-substitution: the `bet × bet` cell composes
-- both surfaces over the chain. This surface is restricted to abs-free
-- bodies (so abstractions only occur inside application subterms, never
-- as the directly substituted shape) and requires an argument-side stack
-- lift premise. See the file docstring in `Pss.Mpss.DeBruijnTypeSafety`
-- for the wall analysis: `body = .bvar 0` at non-empty stack with
-- abstraction-rooted `arg` is genuinely structurally inaccessible.
#print axioms MEqRedStar.argTransportRestricted
#print axioms MEqRedStarArgTransportRestricted_proved
#print axioms MEqRed.app_left
#print axioms MEqRed.app_right
#print axioms MEqRedStar.app_left
#print axioms MEqRedStar.app_right
#print axioms MEqRedStarArgTransportUnderHeadsStack_universal
#print axioms MEqRedStarArgTransportStack.of_generic

-- de Bruijn Lemma 2 `Me-Bet × Me-Bet` cell (chain output, conditional on
-- the argument-transport hypothesis). Composes the proved fused
-- kind-narrowing β-substitution single step with the argument-transport
-- chain to close the diamond at `Term.instantiate 0 v₃ body₃`.
#print axioms EqDiamonds.bet_bet_chain_of

-- Restricted argument-transport surface and the structural stack lift
-- it composes with for `NoBinders` argument shapes. The combination of
-- `Term.AbsFree body` (top-level abs-freedom) and `Term.NoBinders arg`
-- (no `.bvar` and no `.abs` anywhere in the argument) discharges the
-- restricted form of `MEqRedArgTransportPayload` unconditionally modulo
-- kernel axioms. The general payload remains open for the abstraction
-- body and bvar/abstraction argument shapes — see `AXIOMS.md` for the
-- documented residual.
#print axioms Term.NoBinders
#print axioms Term.NoBinders.app_inv
#print axioms Term.NoBinders.absFree
#print axioms Term.NoBinders.scoped_nonempty
#print axioms Term.NoBinders.shiftBy_eq
#print axioms Term.NoBinders.instantiate_eq
#print axioms MEqRedStar.lift_to_any_stack_of_NoBinders
#print axioms MEqRed.preserves_noBinders
#print axioms MEqRedJ.preserves_noBinders
#print axioms MEqRedStar.preserves_noBinders
#print axioms MSubRed.preserves_noBinders
#print axioms MSubRedJ.preserves_noBinders
#print axioms MSubRedStar.preserves_noBinders
#print axioms MEqRed.lift_to_any_context_stack_of_NoBinders_nonempty
#print axioms MEqRedStar.lift_to_any_context_stack_of_NoBinders
#print axioms MEqRedStar.lift_chain_to_any_context_stack_of_NoBinders
#print axioms MEqRedSubBridgePayloadNoBinders_proved
#print axioms MSubRed.lift_to_any_context_stack_of_NoBinders_nonempty
#print axioms MSubRedStar.lift_to_any_context_stack_of_NoBinders
#print axioms MSubRedSubBridgePayloadNoBinders_proved
#print axioms MEqRedArgTransportPayloadRestricted
#print axioms MEqRedArgTransportPayloadRestricted_proved
#print axioms MEqRedArgTransportPayloadNoBinders
#print axioms MEqRedArgTransportPayloadNoBinders_proved

-- The `bet × bet` source cell of de Bruijn Lemma 2 in restricted form:
-- closed for the `Term.AbsFree body₃` ∧ `Term.NoBinders v` case
-- combination, with `NoBinders` propagated through the diamond's
-- argument path via `MEqRed.preserves_noBinders`. This is the partial
-- discharge of `bet_bet_chain_of`'s argument-transport hypothesis for
-- the cases the restricted surface covers.
#print axioms EqDiamonds.bet_bet_chain_AbsFree_of
#print axioms EqDiamonds.bet_bet_chain_NoBinders_of
#print axioms EqDiamonds.bet_bet_chain_ArgNoBinders_of

-- de Bruijn Lemma 2 `Me-App × Me-App` cell (chain output, conditional on
-- the operator stack-head transport hypothesis). Decomposes the closure
-- as "step the arg first, then the operator at the new stack head"
-- using `MEqRedStar.app_right` and `MEqRedStar.app_left`. The transport
-- premise threads the operator-diamond derivation from the original
-- arg-as-stack-head to the joined arg's stack head — this is the
-- structurally missing piece of the de Bruijn Lemma 2 case grid for
-- the `Me-App × Me-App` cell.
#print axioms EqDiamonds.app_app_chain_of
#print axioms MEqRedOpStackHeadTransportPayload
#print axioms MEqRedOpStackHeadTransportPayloadRestricted
#print axioms MEqRedOpStackHeadTransportPayloadRestricted_proved
#print axioms MEqRedStar.op_stack_head_transport_of_NoBinders
#print axioms MSubRedStar.op_stack_head_transport_of_NoBinders
#print axioms EqDiamonds.app_app_chain_from_star_joins_of_NoBinders
#print axioms EqDiamonds.app_app_chain_NoBinders_of

-- de Bruijn Lemma 2 `Me-Bet × Me-App` cell (chain output, conditional on
-- the argument-transport hypothesis and a `.sub`-head bridging hypothesis
-- for the `Me-FOp`-inverted body₂'). Inverts the `app`-side operator step
-- through `Me-FOp`, then composes the proved fused kind-narrowing
-- β-substitution single step with the argument-transport chain.
#print axioms EqDiamonds.bet_app_chain_of
#print axioms EqDiamonds.bet_app_chain_AbsFree_of
#print axioms EqDiamonds.bet_app_chain_NoBinders_of
#print axioms EqDiamonds.bet_app_chain_ArgNoBinders_of
#print axioms EqDiamonds.bet_app_chain_ArgBodyNoBinders_of

-- de Bruijn Lemma 2 `Me-App × Me-Bet` cell (chain output). Symmetric to
-- `bet_app_chain_of`; same conditional hypotheses with LHS/RHS swapped.
#print axioms EqDiamonds.app_bet_chain_of
#print axioms EqDiamonds.app_bet_chain_AbsFree_of
#print axioms EqDiamonds.app_bet_chain_NoBinders_of
#print axioms EqDiamonds.app_bet_chain_ArgNoBinders_of
#print axioms EqDiamonds.app_bet_chain_ArgBodyNoBinders_of

-- de Bruijn Lemma 1 `Ms-Fun × Me-Fun` restricted cell. Discharges the
-- otherwise false same-target `MSubRed` body-narrowing residual when the
-- abstraction body is binder-free.
#print axioms StrongCommutes.fun_fun_BodyNoBinders_of

-- de Bruijn Lemma 1 `Ms-App × Me-App` restricted cell. Discharges both
-- broad operator stack-head transport residuals when the operator source is
-- binder-free.
#print axioms StrongCommutes.app_app_chain_OpNoBinders_of

-- de Bruijn Lemma 1 `StrongCommutes` β-position chain-output cells. These
-- are the analogs of `EqDiamonds.bet_*_chain_of` but for the asymmetric
-- `MSubRed × MEqRed → ∃ t₃, MEqRedStar t₁ t₃ ∧ MSubRedStar t₂ t₃` shape.
-- `MSubRed` has no `bet` constructor; β-fires on the subtype side go
-- through `Ms-Equ` wrapping `Me-Bet`. So the β-position cells are:
--
-- 1. `equ_bet_chain_of`: `Ms-Equ` (wrapping a source `Me-*` step) paired
--    with `Me-Bet`. Delegates to `EqDiamonds.bet_bet_chain_of` /
--    `app_bet_chain_of` based on which `Me-*` constructor the wrap holds,
--    then converts the RHS `MEqRedStar` to `MSubRedStar` via
--    `MSubRedStar.of_MEqRedStar`.
-- 2. `app_bet_chain_of`: `Ms-App` (genuine subtype operator-progression
--    at stack `(v :: s)`) paired with `Me-Bet`. The `Ms-Top` operator
--    case closes at `.top`; `Ms-Equ` delegates to
--    `EqDiamonds.app_bet_chain_of`; `Ms-FOp` β-fires LHS post-step
--    directly using a `.sub`-head bridge for the operator step's
--    `.equ`-head body derivation.
--
-- Both cells are conditional on `MEqRedArgTransportPayload`, the
-- standard body and arg diamond hypotheses, and a `.sub`-head bridging
-- hypothesis matching `EqDiamonds.app_bet_chain_of`'s `hBody₁Sub`.
#print axioms StrongCommutesChain
#print axioms StrongCommutes.equ_bet_chain_of
#print axioms StrongCommutes.app_bet_chain_of
#print axioms StrongCommutes.equ_bet_chain_ArgNoBinders_of
#print axioms StrongCommutes.equ_bet_chain_ArgBodyNoBinders_of
#print axioms StrongCommutes.app_bet_chain_ArgNoBinders_of
#print axioms StrongCommutes.app_bet_chain_ArgBodyNoBinders_of
#print axioms StrongCommutes.app_bet_chain_FOpArgBodyNoBindersAsSub_of
#print axioms StrongCommutes.app_bet_chain_ArgBodyNoBindersAsSub_of
#print axioms StrongCommutes.AppBetNoFalseBridgePayload
#print axioms StrongCommutes.AppBetNoFalseBridgePayload.of_uniform
#print axioms StrongCommutes.FunFunNoFalseNarrowPayload
#print axioms StrongCommutes.FunFunNoFalseNarrowPayload.of_uniform
#print axioms StrongCommutesAppBetBranchPayload
#print axioms StrongCommutesAppBetFOpBranchPayload
#print axioms StrongCommutesAppBetFOpBodyProPayload
#print axioms StrongCommutesAppBetFOpBodyAppPayload
#print axioms StrongCommutesAppBetFOpBodyFunPayload
#print axioms StrongCommutesAppBetFOpBodyFOpPayload
#print axioms StrongCommutesAppBetFOpBranchPayload.of_body_handlers
#print axioms StrongCommutesAppBetBranchPayload.of_fop_handler
#print axioms StrongCommutesFunFunBranchPayload
#print axioms StrongCommutesFunFunBodyProPayload
#print axioms StrongCommutesFunFunBodyAppPayload
#print axioms StrongCommutesFunFunBodyFunPayload
#print axioms StrongCommutesFunFunBranchChainPayload
#print axioms StrongCommutesFunFunBodyAppChainPayload
#print axioms StrongCommutesFunFunBodyAppAppChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubReplacePayload
#print axioms StrongCommutesFunFunBodyAppAppSubReplacePayload_not
#print axioms StrongCommutesFunFunBodyAppAppTransportPayload
#print axioms StrongCommutesFunFunBodyAppAppSubProChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubProHeadChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubProSuccChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubProSuccChainPayload.proved
#print axioms StrongCommutesFunFunBodyAppAppSubTopChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubTopChainPayload.proved
#print axioms StrongCommutesFunFunBodyAppAppSubEquChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubEquChainPayload.proved
#print axioms StrongCommutesFunFunBodyAppAppSubAppChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppProChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppProHeadChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppProSuccChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppProSuccChainPayload.proved
#print axioms StrongCommutesFunFunBodyAppAppSubAppTopChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppTopChainPayload.proved
#print axioms StrongCommutesFunFunBodyAppAppSubAppEquChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppEquChainPayload.proved
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppProChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppProHeadChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppProSuccChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppProSuccChainPayload.proved
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppTopChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppTopChainPayload.proved
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppEquChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppEquChainPayload.proved
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppProChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppProHeadChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppProSuccChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppProSuccChainPayload.proved
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppTopChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppTopChainPayload.proved
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppEquChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppEquChainPayload.proved
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppProChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppProHeadChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppProSuccChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppProSuccChainPayload.proved
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppTopChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppTopChainPayload.proved
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppEquChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppEquChainPayload.proved
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppProChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppProHeadChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppProSuccChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppProSuccChainPayload.proved
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppTopChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppTopChainPayload.proved
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppEquChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppEquChainPayload.proved
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppProChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppProHeadChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppProSuccChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppProSuccChainPayload.proved
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppTopChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppEquChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppTopChainPayload.proved
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppEquChainPayload.proved
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppProChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppProHeadChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppProSuccChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppProSuccChainPayload.proved
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppTopChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppEquChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppTopChainPayload.proved
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppEquChainPayload.proved
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppProChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppProHeadChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppProSuccChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppProSuccChainPayload.proved
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppTopChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppTopChainPayload.proved
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppEquChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppEquChainPayload.proved
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppAppChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppAppProChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppAppProHeadChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppAppProSuccChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppAppProSuccChainPayload.proved
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppAppTopChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppAppTopChainPayload.proved
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppAppEquChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppAppEquChainPayload.proved
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppAppAppChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppAppAppProChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppAppAppProHeadChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppAppAppProSuccChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppAppAppTopChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppAppAppTopChainPayload.proved
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppAppAppEquChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppAppAppEquChainPayload.proved
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppAppAppAppChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppAppAppFOpChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppAppAppChainPayload.of_nested_cases
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppAppAppChainPayload.of_nested_cases_pro_split
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppAppAppAppProChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppAppAppAppProHeadChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppAppAppAppProSuccChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppAppAppAppTopChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppAppAppAppTopChainPayload.proved
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppAppAppAppEquChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppAppAppAppEquChainPayload.proved
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppAppAppAppAppChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppAppAppAppFOpChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppAppAppAppChainPayload.of_nested_cases_pro_split
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppAppAppAppAppProChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppAppAppAppAppProHeadChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppAppAppAppAppProSuccChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppAppAppAppAppTopChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppAppAppAppAppTopChainPayload.proved
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppAppAppAppAppEquChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppAppAppAppAppEquChainPayload.proved
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppAppAppAppAppAppChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppAppAppAppAppAppProChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppAppAppAppAppAppTopChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppAppAppAppAppAppTopChainPayload.proved
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppAppAppAppAppAppEquChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppAppAppAppAppAppAppChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppAppAppAppAppAppFOpChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppAppAppAppAppAppChainPayload.of_nested_cases
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppAppAppAppAppFOpChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppAppAppAppAppChainPayload.of_nested_cases_pro_split
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppAppFOpChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppFOpChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppFOpChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppFOpChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppFOpChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppFOpChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppFOpChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppFOpChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubAppFOpChainPayload
#print axioms StrongCommutesFunFunBodyAppAppSubFOpChainPayload
#print axioms StrongCommutesFunFunBodyAppBetChainPayload
#print axioms StrongCommutesFunFunBodyFunChainPayload
#print axioms StrongCommutesFunFunBranchChainPayload.of_single
#print axioms StrongCommutesFunFunBranchPayload.of_body_handlers
#print axioms StrongCommutesFunFunBranchChainPayload.of_app_fun_handlers
#print axioms StrongCommutesFunFunBodyAppChainPayload.of_app_cases
#print axioms StrongCommutesFunFunBodyAppAppChainPayload.of_sub_cases
#print axioms StrongCommutesFunFunBodyAppAppChainPayload.of_sub_cases_pro_split
#print axioms StrongCommutesFunFunBodyAppAppSubAppChainPayload.of_nested_cases
#print axioms StrongCommutesFunFunBodyAppAppSubAppChainPayload.of_nested_cases_pro_split
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppChainPayload.of_nested_cases
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppChainPayload.of_nested_cases_pro_split
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppChainPayload.of_nested_cases
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppChainPayload.of_nested_cases_pro_split
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppChainPayload.of_nested_cases
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppChainPayload.of_nested_cases_pro_split
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppChainPayload.of_nested_cases
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppChainPayload.of_nested_cases_pro_split
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppChainPayload.of_nested_cases
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppChainPayload.of_nested_cases_pro_split
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppChainPayload.of_nested_cases
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppChainPayload.of_nested_cases_pro_split
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppChainPayload.of_nested_cases
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppChainPayload.of_nested_cases_pro_split
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppAppChainPayload.of_nested_cases
#print axioms StrongCommutesFunFunBodyAppAppSubAppAppAppAppAppAppAppAppAppChainPayload.of_nested_cases_pro_split
#print axioms StrongCommutesFunFunBodyAppAppChainPayload.of_replacements
#print axioms MSubRedOpStackHeadTransportPayload.to_star
#print axioms StrongCommutesFunFunBodyAppAppTransportPayload.of_msub_op_transport
#print axioms StrongCommutes_proved_of_chain_branch_handlers
#print axioms StrongCommutes_proved_of_branch_handlers
#print axioms StrongCommutes_proved_of_split_branch_handlers
#print axioms StrongCommutes_proved_of_split_chain_fun_handlers
#print axioms StrongCommutes_proved_of_split_chain_fun_app_cases_handlers
#print axioms StrongCommutes_proved_of_split_chain_fun_app_operator_handlers
#print axioms StrongCommutes_proved_of_split_chain_fun_app_operator_transport_handlers
#print axioms StrongCommutes_proved_of_split_chain_fun_app_sub_cases_handlers
#print axioms StrongCommutes_proved_of_split_chain_fun_app_sub_cases_top_handlers
#print axioms StrongCommutes_proved_of_split_chain_fun_app_sub_cases_top_equ_handlers
#print axioms StrongCommutes_proved_of_split_chain_fun_app_sub_cases_pro_succ_handlers
#print axioms StrongCommutes_proved_of_split_chain_fun_app_sub_cases_nested_app_handlers

-- Top-level Lemma 1 chain-output closure.
-- Conditional on the same residuals as `EqDiamonds_proved` plus three
-- additional MSub-side residuals (`MSubRedOpStackHeadTransportPayload`,
-- `MSubBridgePayload`, `MSubBodyNarrowPayload`) and a uniform
-- `StrongCommutes` hypothesis. Should depend only on `propext`,
-- `Classical.choice`, `Quot.sound`.
#print axioms MSubRedOpStackHeadTransportPayload
#print axioms MSubRedOpStackHeadTransportPayloadRestricted
#print axioms MSubRedOpStackHeadTransportPayloadRestricted_proved
#print axioms MSubBridgePayload
#print axioms MSubBridgePayload_not
#print axioms MSubBridgePayloadEquNoBinders
#print axioms MSubBridgePayloadEquNoBinders_proved
#print axioms MSubBridgePayloadNoBindersAsSub
#print axioms MSubBridgePayloadNoBindersAsSub_proved
#print axioms MSubBodyNarrowPayload
#print axioms MSubBodyNarrowPayload_not
#print axioms MSubBodyNarrowPayloadNoBinders_proved
#print axioms StrongCommutes_proved

-- Top-level chain-input/chain-output Lemma 1 closure (Path B' wiring).
#print axioms UniformStrongCommutes
#print axioms UniformStrongCommutesChain
#print axioms Lemma_1_DeBruijn_StrongCommutativityStar_proved
#print axioms Lemma_1_DeBruijn_StrongCommutativityChain_proved

-- Top-level Theorem 3 / Theorem 4 / Theorem 5 closures (Path B' wiring).
#print axioms Theorem_3_DeBruijn_TransitivityIsAdmissible_proved
#print axioms Theorem_4_DeBruijn_Progress_proved
#print axioms Theorem_5_DeBruijn_Preservation_proved
#print axioms Theorem_5_DeBruijn_ClosedPreservation_proved

-- Easy `MEqRedPreservesWfM` constructor cases plus partial assembly.
-- The three structural-trivial constructors (`top`, `var`, `tAp`) are
-- discharged unconditionally; the partial assembly leaves the five hard
-- arms (`pro`, `bet`, `app`, `fun_`, `fOp`) as explicit hypotheses, with
-- `fOp` structurally unreachable at empty outer stack.
#print axioms MEqRedPreservesWfM_top
#print axioms MEqRedPreservesWfM_var
#print axioms MEqRedPreservesWfM_tAp
#print axioms MEqRedPreservesWfM_partial

-- Function-bound inversion partial discharge: replaces
-- `AbsFunctionBoundInversion` (one of the load-bearing residuals of
-- Theorem 5) with `UniformStrongCommutes` plus `MEqRedPreservesWfM`,
-- both of which are already named residuals elsewhere in the campaign.
#print axioms AbsFunctionBoundInversion_partial_proved
#print axioms AbsFunctionBoundInversionUnderWfCtx_partial_proved
#print axioms Theorem_5_DeBruijn_Preservation_partial_proved
#print axioms Theorem_5_DeBruijn_ClosedPreservation_partial_proved

end DeBruijn
end Pss
