#import "../style.typ": *

= The Founding Identification <identification>

Inductive values are read by `match`, and `match` is the calculus's _only_ eliminator --- there is no field projection, no tag test, no destructor syntax. Field access _is_ a match; borrowing the second field of a pair _is_ `match b { Pair(_, snd) => … }`. Because a body's arguments are symbolic, matching must work on values the checker knows the type but not the value of, and it is here that a single observation organizes the whole design.

== Refinement is dependent pattern matching

Inside a function body an argument is a symbolic value $sym("")$: an entry of the environment's pure layer whose type the checker knows and whose value it does not. When the checker matches such a scrutinee and enters the branch for constructor $C$, it performs a _comptime write at the scrutinee_ --- the judgment $refi(S, x, C space overline(sym("")), S')$ (@fig-match, `M-OwnedSym`/`M-BorrowSym`) --- which substitutes $C space overline(sym("")))$ for $sym("")$ in _every_ entry and _every_ type across the whole checker state at once. The environment's knowledge is upgraded wholesale: after entering the `S` branch of a match on `n : Nat`, every occurrence of the old snapshot has become `S` $space sym("")'$ for a fresh predecessor $sym("")'$.

This is dependent elimination in the Agda style: by _unification and substitution_, not by threading equality proofs through a motive. And it is _verbatim_ what LLBC's symbolic interpreter already does when it matches a symbolic scrutinee. The identification --- that LLBC's symbolic refinement _is_ dependent pattern matching, one substitution mechanism serving the borrow checker and the type checker alike --- is the founding observation of the calculus, and it explains a restriction that would otherwise look arbitrary: the scrutinee _must be a variable_. Substitution is defined on variables; an arbitrary expression has no substitutable identity to refine. The same fact fixes what refinement may carry --- constructor shapes and equation solutions, facts true of the value timelessly, and never a hole, a marker, or a mutation's result, which are facts about a slot at a moment (@fig-comptime, and the invariant reported in the empirical section).

In a body, this refinement is the runtime symbolic match, and it is fully in force. Case analysis at the _type_ level --- the comptime $arrow.r.squiggly$-reduction of `match` on the pure fragment --- is the one piece deferred to a later substitution discipline for binders (the qualified $arrow.r.squiggly$-match cell of @arrow-map); the identification below concerns the mechanism that is implemented and load-bearing today.

== Fording: a minimal kernel and a derived library

The deepest payoff of the identification is architectural, and it shows in how the calculus handles _equations_. Matching a proof of an identity type is the refl-match: matching `Refl` at `Id A a b` whnf-unifies the two endpoints. If one endpoint is a _flexible_ $sym("")$ --- a substitutable symbolic not occurring in the other side --- it is _solved_ to the other, and the scrutinee's own snapshot is then refined to `Refl` (@fig-match, `M-Refl-Flex`; @fig-comptime, `X-Sol`). The occurs check is real: a $sym("")$ appearing on both sides is not flexible. This _solution transition_, together with its occurs check, is the _entire_ unification vocabulary the kernel implements. When both endpoints whnf to rigid heads, the match is simply _stuck_ --- there is no rule.

Everything a full dependent-pattern-match unifier would additionally do --- no-confusion between distinct constructors, injectivity of a constructor, uniqueness of identity proofs, discharge of a conflicting equation as absurd --- is _not_ a kernel operation. It is a _derived library_, written inside the calculus as ordinary well-typed terms over the two identity eliminators (Paulin-Mohring `j` and Streicher `k`, @fig-typing, `T-Elim-J`/`T-Elim-K`): constructor injectivity is a term `injProof` built from `j`; UIP is `uipProof` built from `k`; no-confusion for `Nat` is a `j`-spine landing in a reducing code type that computes to $bot$. These are _mechanized facts_, checked in the same kernel as every other program, with no machine rule beyond the eliminators' own typing. This is _fording_: rather than teach the kernel a unification algorithm, the calculus keeps the kernel to substitution-plus-occurs-check and recovers the algorithm's consequences as a library of provable identities. The metatheoretic surface shrinks accordingly --- there is one transition to trust, not a case analysis of unification steps.

== The recursive-family encoding

Native indexed families arrive with the fording kit; until then, an indexed type such as `Vec` lives in the calculus as its _recursive-family encoding_, computed from its index by large elimination:
$
  "Vec" T space Z equiv top, quad "Vec" T space (S space n) equiv T times ("Vec" T space n),
$
with `VNil` and `VCons` as notation for the unit value and pairing, and the index argument vanishing. The load-bearing property is that the type _computes under a stuck index_: `Vec T (S` $space sym("")$`)` unfolds to `T × (Vec T` $space sym("")$`)` even while the length $sym("")$ is unknown, which is exactly what large elimination provides and exactly what a checker running over symbolic arguments needs. (One consequence is presentation-specific and does not survive to native families: with no index argument at the constructor, more write orders type-check than the indexed form would force; that sharpening returns with native `VCons`.)

== The money test, mechanized

The mechanism behind the money test of the introduction is now nameable. A constructor application is checked by _inhabitation against a type that must compute_ (@fig-typing, `T-Ctor`): the expected type is reduced toward canonical form, and the constructor's fields are checked against the arguments its signature then demands. A _stuck_ type --- one whose head will not reduce because it awaits an unknown snapshot --- admits no constructor; the check is a table lookup that misses, and the audit returns false. This is not a rule against forgotten updates; it is the ordinary constructor-checking rule meeting a type the program left un-computed. In the $Sigma$-paired vector push, the omitted `*l := S(*l)` leaves the second field expected at the stuck `Vec T` $space sym("")$ while the value on hand is a `Vec T (S` $space sym("")$`)`; the two do not converge, and the boundary audit rejects. Supply the update and the expected type computes to a form the value inhabits. The dependent guarantee is carried entirely by _what conversion has to say yes to_, and the ownership machinery --- suspension, contract-free siblings, the single boundary audit --- is what makes the in-place mutation that provokes the check safe to write in the first place. The two are indispensable together, and they meet in one interpreter.
