#import "../style.typ": *

= The Founding Identification <identification>

Inductive values are read by `match`, and `match` is the calculus's _only_ eliminator --- there is no field projection, no tag test, no destructor syntax. Field access _is_ a match; borrowing the second field of a pair _is_ `match b { Pair(_, snd) => … }`. Because a body's arguments are symbolic, matching must work on values the checker knows the type but not the value of, and it is here that a single observation organizes the whole design.

== Refinement is dependent pattern matching

Inside a function body an argument is a symbolic value $sym("")$: an entry of the environment's pure layer whose type the checker knows and whose value it does not. When the checker matches such a scrutinee and enters the branch for constructor $C$, it performs a _comptime write at the scrutinee_ --- the judgment $refi(S, x, C space overline(sym("")), S')$ (@fig-match, #smallcaps[M-OwnedSym]/#smallcaps[M-BorrowSym]) --- which substitutes $C space overline(sym(""))$ for $sym("")$ in _every_ entry and _every_ type across the whole checker state at once. The environment's knowledge is upgraded wholesale: after entering the `S` branch of a match on `n : Nat`, every occurrence of the old snapshot has become `S` $space sym("")'$ for a fresh predecessor $sym("")'$.

This is dependent elimination in the Agda style: by _unification and substitution_, not by threading equality proofs through a motive. And it is _verbatim_ what LLBC's symbolic interpreter @ho-fromherz-protzenko-2024 already does when it matches a symbolic scrutinee. The identification --- that LLBC's symbolic refinement _is_ dependent pattern matching, one substitution mechanism serving the borrow checker and the type checker alike --- is the founding observation of the calculus, and it explains a restriction that would otherwise look arbitrary: the scrutinee _must be a variable_. Substitution is defined on variables; an arbitrary expression has no substitutable identity to refine. The same fact fixes what refinement may carry --- constructor shapes and equation solutions, facts true of the value timelessly, and never a hole, a marker, or a mutation's result, which are facts about a slot at a moment (@fig-comptime, and the invariant reported in the empirical section).

In a body, this refinement is the runtime symbolic match, and it is fully in force. Case analysis at the _type_ level --- the comptime $arrow.r.squiggly$-reduction of `match` on the pure fragment --- is the one piece deferred to a later substitution discipline for binders (the qualified $arrow.r.squiggly$-match cell of @arrow-map); the identification below concerns the mechanism that is implemented and load-bearing today.

== The second layer: branch equations

Substitution is a complete account of branch knowledge for one kind of body and an incomplete account for another, and which kind you are in is decided by whether the body has to _produce_ evidence. Under the conformance architecture (@sec-architectures) it never does: the body carries zero proof obligations, so having every occurrence of the scrutinee rewritten is everything a body could want, and the identification above is the whole story. Under direct propositional proving the body must hand its caller a proof, and there the account runs out --- at exactly one place, and for an instructive reason.

The place is a _stuck_ split. When a match scrutinee whnf-reduces not to a bare $sym("")$ but to a neutral spine --- `leb` $space sym("x") space sym("p")$, the shape every comparison-driven algorithm produces --- there is no substitutable identity to refine, so the checker first _generalizes_: it mints a fresh $sym("b") : "Bool"$ and abstracts the spine to it across the whole state (@fig-comptime, #smallcaps[X-Gen]), after which the branch refines $sym("b")$ to `True` as an ordinary symbolic split. Everything that _already_ mentioned the spine now reads `True`. But a body that writes `leb x p` _after_ the split re-derives the spine from scratch, and what it derives is a term the abstraction never saw; nothing rewrites it, and the body learns nothing from the branch it is standing in. The natural thing to write, `Refl : Id Bool (leb x p) True`, is rejected --- and rightly, on the calculus's own terms: `Refl` inhabits an identity only when its endpoints _convert_ (@fig-typing, #smallcaps[T-Ctor]), and `leb` $space sym("x") space sym("p")$ does not convert with `True`. That non-conversion is precisely what made the scrutinee stuck in the first place; had the endpoints converged there would have been nothing to generalize.

So the mechanism has two layers, and the imperative fragment had only the first. Motive abstraction --- generalization, then refinement --- handles _occurrences_. _Knowledge_ is a separate obligation, and the pure fragment had always discharged it with a convoy motive, carrying `Id Bool` $space chevron.l "spine" chevron.r space b$ through the elimination so each arm receives the equation as an argument. The rule below gives the body's `match` the same second layer:

$
  "match" space h : x space { thin overline("br") thin }
$

binds, in every branch, an equation $h : "Id" space tau space chevron.l "the scrutinee's pre-split value" chevron.r space chevron.l "this branch's constructor" chevron.r$. One binder serves the whole match, since only its _type_ varies per branch. It is _declared_, not inferred: without the binder nothing is bound and nothing is minted, so no existing program changes. And it is sound for exactly the reason the substitution is sound --- the branch is entered precisely when the scrutinee evaluates to that constructor, so the equation is a fact about the value, true at entry and true forever. That is the same standard the identification above imposes on what refinement may _carry_ --- constructor shapes and equation solutions, never a hole, a marker, or a mutation's result --- now applied to what it may _reify_. The rule adds no new kind of knowledge; it makes the branch's existing knowledge citable.

The interesting part is what it costs, because the answer is: nothing, exactly where it was already free. The equation's content is entirely determined by what happened to the pre-split value. At an ordinary symbolic split the ⇜ refinement (#smallcaps[X-Shape]) has already rewritten that value to this branch's constructor _everywhere_, so the equation's two endpoints are literally identical and $h$ is inhabited by `Refl` --- no symbolic value minted, no $Gamma_sigma$ entry, nothing carried. On a concrete scrutinee, likewise. Only at a stuck split is the equation a genuine hypothesis, and only because generalization is the one thing that makes a pre-split value _unnameable_ afterwards. The implementation follows the distinction exactly: #smallcaps[X-Gen] returns the normalized pre-abstraction spine alongside $sym("b")$, and the branch setup mints a single fresh $sym("")$ typed `Id Bool` $space chevron.l "spine" chevron.r space chevron.l C chevron.r$, registered in $Gamma_sigma$ _before_ the refinement fires so that it is swept along with every other $sym("")$-bearing component of the state --- the same discipline that keeps obligations and the pinned return type current, and therefore no new update path. (One narrowness is inherited: #smallcaps[X-Gen] mints only `Bool` generalizations, so the hypothesis form available today is always an `Id Bool`.)

The shape is standard --- Lean's `match h : x with`, Rocq's `destruct … eqn:` --- and saying so is the point rather than a caveat: the calculus reaches the same construct from the other side. In a conventional elaborator the equation is _always_ a real hypothesis, because nothing substitutes into the goal on the programmer's behalf; here substitution does the work almost everywhere, and the equation is needed only in the one case where abstraction has _replaced_ substitution. The two-layer decomposition is thus not a design choice imported from prior art but a distinction the symbolic interpreter forced, and the prior art is what confirms the resolution.

What it buys is the relational partition, and through it the case study's headline. The partition's postcondition bounds its two parts (`Ub p (*v)` for the part it keeps, `Lb p hi` for the part it returns); its body branches on `leb x p` and must therefore _produce_ `Le x p` on one side and `Le p x` on the other, from the branch it took. Both come from the equation and from nothing else --- `leb_true_le x p h` on the `True` side, and `leb_false_gt` weakened by one on the `False` side. Neither derivation exists without the rule, and the mechanization keeps the pair adjacent on purpose: the same body with `Refl` in place of $h$ is the rejected wall test, and the same body with $h$ is accepted, one binder the only difference between them. Downstream of that partition is the whole-list quicksort whose return type is `Sorted (*v)` together with count-preservation against `old *v`, carrying no declared backward specification anywhere in its call tree.

== Fording: a minimal kernel and a derived library

The deepest payoff of the identification is architectural, and it shows in how the calculus handles _equations_. Matching a proof of an identity type is the refl-match: matching `Refl` at `Id A a b` whnf-unifies the two endpoints. If one endpoint is a _flexible_ $sym("")$ --- a substitutable symbolic not occurring in the other side --- it is _solved_ to the other, and the scrutinee's own snapshot is then refined to `Refl` (@fig-match, #smallcaps[M-Refl-Flex]; @fig-comptime, #smallcaps[X-Sol]). The occurs check is real: a $sym("")$ appearing on both sides is not flexible. This _solution transition_, together with its occurs check, is the _entire_ unification vocabulary the kernel implements. When both endpoints whnf to rigid heads, the match is simply _stuck_ --- there is no rule.

Everything a full dependent-pattern-match unifier would additionally do --- no-confusion between distinct constructors, injectivity of a constructor, uniqueness of identity proofs, discharge of a conflicting equation as absurd --- is _not_ a kernel operation. It is a _derived library_, written inside the calculus as ordinary well-typed terms over the two identity eliminators (Paulin-Mohring `j` and Streicher `k`, @fig-typing, #smallcaps[T-Elim-J]/#smallcaps[T-Elim-K]): constructor injectivity is a term `injProof` built from `j`; UIP is `uipProof` built from `k`; no-confusion for `Nat` is a `j`-spine landing in a reducing code type that computes to $bot$. These are _mechanized facts_, checked in the same kernel as every other program, with no machine rule beyond the eliminators' own typing. This is _fording_: rather than teach the kernel a unification algorithm, the calculus keeps the kernel to substitution-plus-occurs-check and recovers the algorithm's consequences as a library of provable identities. The metatheoretic surface shrinks accordingly --- there is one transition to trust, not a case analysis of unification steps.

== The recursive-family encoding

Native indexed families arrive with the fording kit; until then, an indexed type such as `Vec` lives in the calculus as its _recursive-family encoding_, computed from its index by large elimination:
$
  "Vec" T space Z equiv top, quad "Vec" T space (S space n) equiv T times ("Vec" T space n),
$
with `VNil` and `VCons` as notation for the unit value and pairing, and the index argument vanishing. The load-bearing property is that the type _computes under a stuck index_: `Vec T (S` $space sym("")$`)` unfolds to `T × (Vec T` $space sym("")$`)` even while the length $sym("")$ is unknown, which is exactly what large elimination provides and exactly what a checker running over symbolic arguments needs. (One consequence is presentation-specific and does not survive to native families: with no index argument at the constructor, more write orders type-check than the indexed form would force; that sharpening returns with native `VCons`.)

== The money test, mechanized

The mechanism behind the money test of the introduction is now nameable. A constructor application is checked by _inhabitation against a type that must compute_ (@fig-typing, #smallcaps[T-Ctor]): the expected type is reduced toward canonical form, and the constructor's fields are checked against the arguments its signature then demands. A _stuck_ type --- one whose head will not reduce because it awaits an unknown snapshot --- admits no constructor; the check is a table lookup that misses, and the audit returns false. This is not a rule against forgotten updates; it is the ordinary constructor-checking rule meeting a type the program left un-computed. In the $Sigma$-paired vector push, the omitted `*l := S(*l)` leaves the second field expected at the stuck `Vec T` $space sym("")$ while the value on hand is a `Vec T (S` $space sym("")$`)`; the two do not converge, and the boundary audit rejects. Supply the update and the expected type computes to a form the value inhabits. The dependent guarantee is carried entirely by _what conversion has to say yes to_, and the ownership machinery --- suspension, contract-free siblings, the single boundary audit --- is what makes the in-place mutation that provokes the check safe to write in the first place. The two are indispensable together, and they meet in one interpreter.
